JetBrains/intellij-plugin-verifier

- README.md
There are two GitHub Actions available in the market that wrap IntelliJ Plugin Verifier to let automate the verification process of the plugins with GitHub Actions CI.
It's worth to promote them so verifier will be used by the wider group of the developers.
> Add Integration section to the README

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/utils/FileUtil.kt
Hi :wave: I think this pull request should fix this error:
```
Exception in thread "main" java.lang.IllegalArgumentException: JDK /home/rachel/tools/jdk misses mandatory jars: rt.jar
at com.jetbrains.pluginverifier.jdk.JdkDescriptorCreator.createPreJava9(JdkDescriptorCreator.kt:97)
at com.jetbrains.pluginverifier.jdk.JdkDescriptorCreator.createJdkDescriptor(JdkDescriptorCreator.kt:45)
at com.jetbrains.pluginverifier.jdk.JdkDescriptorCreator.createJdkDescriptor(JdkDescriptorCreator.kt:29)
at com.jetbrains.pluginverifier.jdk.JdkDescriptorCreator.createJdkDescriptor$default(JdkDescriptorCreator.kt:28)
at com.jetbrains.pluginverifier.ide.IdeDescriptor$Companion.create(IdeDescriptor.kt:59)
at com.jetbrains.pluginverifier.options.OptionsParser.createIdeDescriptor(OptionsParser.kt:66)
at …
```
> Fix: support a symbolic link for JAVA_HOME

- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/filtering/documented/DocumentedProblemsPageVerifierMain.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/filtering/documented/DocumentedProblemsPagesFetcher.kt
For the docs testing purposes, we'd like to parameterize `DocumentedProblemsPageVerifierMain` class to be able to provide repository and branch that will be used for the page verification, like:
java -cp verifier-all.jar com.jetbrains.pluginverifier.filtering.documented.DocumentedProblemsPageVerifierMain hsz/intellij-sdk-docs dev-branch
> DocumentedProblemsPageVerifierMain: add repository and branch parameters

- README.md
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/PluginVerifierMain.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/CmdOpts.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/OptionsParser.kt
Added `-offline` CLI property that allows to run Plugin Verifier without internet
> MP-3298: support running in offline mode.

- plugins-verifier-service/build.gradle
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105
> Update log4j to 2.17 to address CVE-2021-45105.

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/beans/PluginBean.java
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/MockPluginsTest.kt
- intellij-plugin-structure/tests/src/test/resources/mock-plugin/META-INF/plugin.xml
- intellij-plugin-structure/tests/src/test/resources/mock-plugin/intellij.v2.module-ultimate.xml
- intellij-plugin-structure/tests/src/test/resources/mock-plugin/intellij.v2.module.xml
- intellij-plugin-structure/tests/src/test/resources/mock-plugin/optionalsDir/ultimate-plugin.xml
Such functionality is needed for Kotlin plugin:
- one <content> block we have in the main plugin.xml file
- another comes from <include> block with kotlin-ultimate part.
Corresponding functionality was supported in the IDEA core by the commit:
https://github.com/JetBrains/intellij-community/commit/0f9bf52acebf3801e5a84690bfe7b5d96ad503ed
> Support multiple <content> blocks in the plugin.xml

- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/CmdOpts.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkIde/CheckIdeParams.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkIde/CheckIdeParamsBuilder.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkIde/CheckIdeTask.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkPlugin/CheckPluginParams.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkPlugin/CheckPluginParamsBuilder.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkPlugin/CheckPluginTask.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkPluginApi/CheckPluginApiParams.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkPluginApi/CheckPluginApiParamsBuilder.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkPluginApi/CheckPluginApiTask.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkTrunkApi/CheckTrunkApiParams.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkTrunkApi/CheckTrunkApiParamsBuilder.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkTrunkApi/CheckTrunkApiTask.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/PluginVerifier.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/VerificationRunner.kt
- plugins-verifier-service/src/main/kotlin/org/jetbrains/plugins/verifier/service/service/verifier/VerifyPluginTask.kt
Add exclude-external-build-classes-selector option to have the ability to verify JetBrains plugins without checking external classes. It is useful for verifying of Kotlin plugin, because checking of JPS classes only create false-positives.
> Add exclude-external-build-classes-selector option

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/utils/FileUtil.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/extractor/PluginExtractor.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/PluginFileErrors.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/MockPluginsTest.kt
https://youtrack.jetbrains.com/issue/MP-4275
Right now IDE accepts only two types of plugin archives:
.jar archive
.zip archive with structure <Plugin Id>/lib/*.jar
The problem is that Marketplace accepts .zip archives that contain only .jar archive. Marketplace should only accept archives mentioned above.
> Do not accept incorrect plugin archives

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/InvalidDescriptorErrors.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/MinorWarnings.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/domain/IdeTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/InvalidPluginsTest.kt
https://youtrack.jetbrains.com/issue/MP-3644
To prevent uploading a plugin with some mistakes on the uploading stage
Ideas what we can check in the library. Done in this branch:
1. The plugin name is present and different from the default value;
2. Plugin description is present and differs from the default value in both Plugin template and DevKit;
3. Plugin name does not include the word "plugin" (except those who already have it — for new plugins only);
4. Description in English is present;
5. Plugin name doesn't include: JetBrains, IDEA, PyCharm, CLion, AppCode, DataGrip, Fleet, GoLand, PhpStorm, WebStorm, Rider, ReSharper, TeamCity, YouTrack, RubyMine, IntelliJ (except those who already have it — for new plugins only);
8. Links to images in the plugin description must be with HTTPS, …
> Add additional checks for ij updates

- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/internal/InternalApiUsageProcessor.kt
- intellij-plugin-verifier/verifier-test/after-idea/src/main/java/internal/hierarchy/IntermediateInternalClass.java
- intellij-plugin-verifier/verifier-test/after-idea/src/main/java/internal/hierarchy/PublicConcreteClass.java
- intellij-plugin-verifier/verifier-test/after-idea/src/main/java/internal/hierarchy/PublicInterface.java
- intellij-plugin-verifier/verifier-test/before-idea/src/main/java/internal/hierarchy/IntermediateInternalClass.java
- intellij-plugin-verifier/verifier-test/before-idea/src/main/java/internal/hierarchy/PublicConcreteClass.java
- intellij-plugin-verifier/verifier-test/before-idea/src/main/java/internal/hierarchy/PublicInterface.java
- intellij-plugin-verifier/verifier-test/mock-plugin/src/main/java/mock/plugin/internal/noWarning/NoWarnings.java
Proof of concept fix for https://youtrack.jetbrains.com/issue/MP-4620
The factoring is not great, but does contain a test case to show the issue
> MP-4620: Add check to internal API usage if method call is invoking a public API but implemented in internal class

- intellij-plugin-verifier/verifier-core/src/main/java/com/jetbrains/pluginverifier/verifiers/resolution/MethodResolver.kt
- intellij-plugin-verifier/verifier-test/mock-plugin/src/main/java/mock/plugin/invokeDynamic/NoErrorOnIndy.java
- intellij-plugin-verifier/verifier-test/mock-plugin/src/main/java/mock/plugin/invokeDynamic/SomeClass.java
Add support for `VarHandle` which allows to access fields using
Ref: [MP-4313](https://youtrack.jetbrains.com/issue/MP-4313/False-positive-runPluginVerifier-task-report-compatibility-problem-when-using-VarHandle-This-can-lead-to-NoSuchMethodError)
Ref: https://docs.oracle.com/javase/specs/jvms/se9/html/jvms-6.html
----
So my plugins targets JDK11+ based IntelliJs. For some reasons I had to access a private variable in a class that I don't own. So I just used a `VarHandle`, this works fine in reality.
However I was surprised the plugin verifier reported the `VarHandle` use as incompatible because the _`invokevirtual` bytecode references an unresolved method that could lead to **NoSuchMethodError** exception at runtime_ (see log below).
```
...
Compatibility problems (1): 
#Invocation of …
```
> MP-4313: Add support for VarHandle as well

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/beans/PluginDependencyBean.java
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/javaPlugin/JavaPluginApiCompatibilityIssueAnalyzer.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/javaPlugin/UndeclaredDependencyOnJavaPluginProblem.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/verifiers/CompatibilityIssueAnalyzer.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/verifiers/PluginVerificationContext.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/UndeclaredDependencyOnJavaPluginTest.kt
- Migrate warning to error
- Move verification logic to a separate class. This decouples the verification context from verification business logic.
https://youtrack.jetbrains.com/issue/MP-5434
> Increase severity for "does not declare explicit dependency on Java plugin" to an error

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/problems/InvalidDescriptorErrors.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/IdePluginManager.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/InvalidDescriptorErrors.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/PluginXmlValidationTest.kt
Optional dependency in plugin descriptor with an empty `config-file` is treated as an error.
> Treat optional dependency with an empty file as an error

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/problems/InvalidDescriptorErrors.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/verifiers/DependenciesVerifiers.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/verifiers/ReusedDescriptorVerifierTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/InvalidPluginsTest.kt
Multiple dependencies cannot reuse the same descriptor file.
It is now a plugin descriptor error when such thing happens.
See [IDEA-261692](https://youtrack.jetbrains.com/issue/IDEA-261692/Highlight-error-in-plugin.xml-if-several-dependencies-use-the-same-descriptor-file) and [MP-3391](https://youtrack.jetbrains.com/issue/MP-3391/Verifier-error-when-several-dependencies-use-the-same-descriptor-file)
> Dependencies in the descriptor cannot reference the same descriptor file

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/plugin/PluginProblem.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/problems/InvalidDescriptorErrors.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/problems/ProblemSolutionHint.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/InvalidPluginsTest.kt
Create better description of empty <vendor> element.
Missing vendor will create an improved message:
```
Invalid plugin descriptor 'plugin.xml': <vendor> element has no content. The vendor name or organization ID must be set. Example: <vendor email="joe@example.com">Joe Doe</vendor>
```
> Create better description of empty <vendor>

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/problems/InvalidDescriptorErrors.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/verifiers/ReusedDescriptorVerifierTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/InvalidPluginsTest.kt
Decrease level when several dependencies use the same descriptor file from _error_ to _warning_.
See [MP-5523](https://youtrack.jetbrains.com/issue/MP-5523/Verifier-decrease-level-to-Warning-when-several-dependencies-use-the-same-descriptor-file)
> Decrease level when several dependencies use the same descriptor

- intellij-plugin-structure/structure-edu/src/main/kotlin/com/jetbrains/plugin/structure/edu/EduPlugin.kt
- intellij-plugin-structure/structure-edu/src/main/kotlin/com/jetbrains/plugin/structure/edu/EduPluginManager.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/edu/mock/EduPluginMockTest.kt
- intellij-plugin-structure/tests/src/test/resources/edu/course_obsolete_programming_lang_and_version.json
This is a workaround on complex, strange and outdated logic about xml id generation. Long story short:
1. There was no xml id for edu plugins, so we need to generate it by our self. The original generation alg was 
`"${this.title}_${this.vendor?.name}_$programmingLanguage"`
2. Then, it appears that authors should be able to change the `title`. To do so, edu team introduced `generated_edu_id` field in course json. The idea is to generate it the same way as described in (1) in the edu plugin and only after that allow author to change the `title`.
3. Now, it appears that `programmingLanguage` could contain the programming language, and it's version divided by space. Edu also want to split `programmingLanguage` to `programmingLanguageId` and `programmingLanguageVersion`. Also, …
> Workaround for edu programming language

- gradle/libs.versions.toml
- intellij-feature-extractor/build.gradle.kts
- intellij-plugin-verifier/build.gradle.kts
- plugins-verifier-service/build.gradle.kts
- Bumps `commons-io` to 2.12.0
- Removes `commons-io` as an explicit dependencies from projects that don't use this anymore
> Bump commons-io to 2.12.0 while removing outdated usages

- intellij-plugin-verifier/verifier-core/src/main/java/com/jetbrains/pluginverifier/verifiers/method/KotlinMethods.kt
- intellij-plugin-verifier/verifier-core/src/main/java/com/jetbrains/pluginverifier/verifiers/method/MethodArgumentTypesVerifier.kt
- intellij-plugin-verifier/verifier-core/src/main/java/com/jetbrains/pluginverifier/verifiers/method/MethodLocalVarsVerifier.kt
- intellij-plugin-verifier/verifier-core/src/main/java/com/jetbrains/pluginverifier/verifiers/method/MethodReturnTypeVerifier.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/PluginVerifier.kt
- intellij-plugin-verifier/verifier-test/after-idea/src/main/kotlin/internal/defaultMethod/AnInternalType.kt
- intellij-plugin-verifier/verifier-test/after-idea/src/main/kotlin/internal/defaultMethod/InterfaceWithDefaultMethodUsingInternalAPI.kt
- intellij-plugin-verifier/verifier-test/after-idea/src/main/kotlin/internal/defaultMethod/TopInterfaceWithDefaultMethodUsingInternalAPI.kt
- intellij-plugin-verifier/verifier-test/before-idea/src/main/kotlin/internal/defaultMethod/AnInternalType.kt
- intellij-plugin-verifier/verifier-test/before-idea/src/main/kotlin/internal/defaultMethod/InterfaceWithDefaultMethodUsingInternalAPI.kt
- intellij-plugin-verifier/verifier-test/before-idea/src/main/kotlin/internal/defaultMethod/TopInterfaceWithDefaultMethodUsingInternalAPI.kt
- intellij-plugin-verifier/verifier-test/mock-plugin/src/main/kotlin/mock/plugin/internal/defaultMethod/NoInternalTypeUsage.kt
- intellij-plugin-verifier/verifier-test/mock-plugin/src/main/kotlin/mock/plugin/internal/defaultMethod/NotInternalTypeUsage.kt
Kotlin default methods work differently than JVM default methods, as the compiler is generation the default implementation in an inner class `DefaultImpls`, and the kotlin compiler will generate the method in the implementor, even if the actual code doesn't use it.
This PR addresses that by identifying Kotlin default methods in implementation and skip from analyzing these methods for internal types.
Three verifiers had to be patched
- method arguments
- method local vars
- return type
Reference : [MP-5395](https://youtrack.jetbrains.com/issue/MP-5395/Reports-internal-usage-when-extending-an-interface-with-default-method-having-internal-type)
------------
Take this interface from IntelliJ, where `getPlaceholderCollector` uses the internal type `CodeVisionPlaceholderCollector`
```kotlin …
```
> MP-5395: Skip Kotlin default methods from internal usage check

- gradle/libs.versions.toml
- ide-diff-builder/build.gradle.kts
- intellij-feature-extractor/build.gradle.kts
- intellij-plugin-structure/build.gradle.kts
- intellij-plugin-verifier/build.gradle.kts
- plugins-verifier-service/build.gradle.kts
Since Kotlin 1.8, 'kotlin-stdlib-jdk8' has been merged to stdlib. See https://kotlinlang.org/docs/whatsnew18.html#updated-jvm-compilation-target
Kotlin Gradle plugin adds 'kotlin-stdlib' automatically to all source sets. See https://kotlinlang.org/docs/gradle-configure-project.html#dependency-on-the-standard-library
> Remove dependency on kotlin-stdlib and kotlin-stdlib-jdk8

- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/IntelliJPlatformProduct.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginVendors.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/MinorWarnings.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/UnacceptableWarnings.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/verifiers/PluginIdVerifier.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/verifiers/ProblemRegistrar.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/verifiers/SimpleVerifiers.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/plugin/PluginVendorsTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/verifiers/PluginIdVerifierTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/InvalidPluginsTest.kt
See [MP-5459](https://youtrack.jetbrains.com/issue/MP-5459)
Stricter rules for plugin IDs:
- specific words in plugin IDs are discouraged and treated as _warnings_
- specific plugin prefixes are discouraged and treated as _unnaceptable warnings_, such as `com.example` or JetBrains prefixes
> Validate plugin IDs for specific prefixes and product names

- intellij-plugin-verifier/gradle/libs.versions.toml
- intellij-plugin-verifier/verifier-test/build.gradle.kts
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/mocks/TestJdkDescriptorProvider.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/mocks/TestJdkDescriptorProviderTest.kt
When discovering JDK for mock plugins and their descriptors, investigate
1. `pluginverifier.testjava.home` system property
2. `JAVA_HOME` environment variable
3. SDKMan common location (MacOS)
4. `java.home` system property 
5. fixed paths (Linux).
> Improve discovery of Java JDK for mock plugins

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginVendors.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/plugin/PluginVendorsTest.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/PluginVerificationResult.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/PluginVerifier.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/filtering/ApiUsageFilter.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/filtering/InternalApiUsageFilter.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/InternalApiUsagePluginTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/VerificationRunner.kt
See [MP-3282](https://youtrack.jetbrains.com/issue/MP-3282)
- introduce `ApiUsageFilter` to classify API usages to relevant and irrelevant. This is in the same vein as `ProblemsFilter`
- `PluginVerifier` may be provided with list of `ApiUsageFilter`-s.
- a `InternalApiUsageFilter` for JetBrains-related plugins is introduced. This is not enabled by default. It allows to ignore internal API usages from internal plugins.
- a new field -- `ignoredInternalApiUsages` is introduced in the `PluginVerificationResult`. This contains internal API usages that have been filtered out by any of the `ApiUsageFilter`-s.
- a parametric test that uses ByteBuddy to create multiple variants of API usages has been introduced in `InternalApiUsagePluginTest`.
> Ignore internal API usages from internal plugins

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/InvalidDescriptorErrors.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/MinorWarnings.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/verifiers/ExtensionPointVerifiers.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/PluginXmlValidationTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/verifiers/ServiceExtensionPointPreloadVerifierTest.kt
Service EP preloading is no longer supported. Add a rule to detect this and emit a warning.
See [MP-5530](https://youtrack.jetbrains.com/issue/MP-5530/Plugin-Verifier-mark-Service-EP-preload-attribute-as-warning)
> Treat Service EP 'preload' attribute as an error

- README.md
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/CmdOpts.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/OptionsParser.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/output/OutputFormat.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/output/OutputOptions.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/output/markdown/MarkdownResultPrinter.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkIde/CheckIdeResultPrinter.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkPlugin/CheckPluginParams.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkPlugin/CheckPluginResult.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkPlugin/CheckPluginResultPrinter.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkPlugin/CheckPluginTask.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/twoTargets/TwoTargetsResultPrinter.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/nonExtendable/NonExtendableTypeInherited.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/output/markdown/MarkdownOutputTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/cli/OptionsParserTest.kt
Support Markdown output format for verification reports.
Enable `-vrf` or `-verification-reports-formats` CLI switch that enables multiple output formats: plain, HTML and Markdown. By default, Markdown is disabled.
Reports are emitted into the same directory as HTML outputs, with `report.markdown` being the default filename.
Plugin Problem messages are not in Markdown. This is out of scope of this PR.
> Support Markdown output format for verification reports

- README.md
The documentation says `-ignore-problems` but [it seems like](https://github.com/JetBrains/intellij-plugin-verifier/blob/639ae7ebbc433a81dd956564be57e4514d504ea7/intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/CmdOpts.kt#L17C1-L17C1) the actual name of that argument is `-ignored-problems`.
> Typo in argument name in README.md

- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/PluginVerifierMain.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/output/html/HtmlResultPrinter.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/reporting/DirectoryBasedPluginVerificationReportage.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/reporting/LoggingPluginVerificationReportageAggregator.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/reporting/PluginVerificationReportageAggregator.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/reporting/LoggingPluginVerificationReportageAggregatorTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/mocks/MockLogger.kt
In CLI, show the verification reports directory at the end of verification process.
```
2023-08-31T09:14:35 [main] INFO  verification - Total time spent downloading plugins and their dependencies: 0 ms
2023-08-31T09:14:35 [main] INFO  verification - Total amount of plugins and dependencies downloaded: 0 B
2023-08-31T09:14:35 [main] INFO  verification - Total amount of space used for plugins and dependencies: 528.57 MB
...
2023-08-31T09:14:35 [main] INFO  verification - Verification reports for example-plugin:25-SNAPSHOT saved to /Users/novotnyr/projects/jetbrains/intellij-plugin-verifier/plugins-verifier-service/verification-2023-08-31 at 09.14.26/IE-203.7717.75
Process finished with exit code 0
```
> Show verification reports directory at the end of verification in CLI

- README.md
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/OptionsParser.kt
- intellij-plugin-verifier/verifier-test/build.gradle.kts
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/cli/OptionsParserTest.kt
When the `-vrf` parameter is missing, a default set of verification output format is used. This is to maintain the backwards compatibility.
However, in order to integrate with [Gradle IntelliJ Plugin](https://github.com/JetBrains/gradle-intellij-plugin), we need to explicitly indicate an empty list of verification output formats.
Due to the `spullara/cli-parser` and its handling of empty arrays, an empty string literal passed as a CLI argument, is used to indicate an empty array of output formats.
> Indicate no verification output formats with an explicit empty string

- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/output/markdown/MarkdownResultPrinter.kt
Change Markdown verification report extension to `.md`. This is a common convenience and better than `.markdown`.
> Change Markdown verification report extension to ".md"

- README.md
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/CmdOpts.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkPlugin/CheckPluginParams.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkPlugin/CheckPluginParamsBuilder.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkPlugin/CheckPluginTask.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tasks/checkPlugin/CheckPluginParamsBuilderTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/mocks/MockPluginDetailsCache.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/mocks/MockPluginVerificationReportage.kt
Add a `--suppress-internal-api-usages` switch to disable internal API usages reporting by internal plugins.
See #952 for original implementation, which did not provide CLI switch.
> CLI switch to suppress internal API usages by internal plugins

- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/PluginVerifierMain.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/profiling/PluginVerificationProfilings.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/reporting/DurationMeasuringPluginVerificationReportageTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/reporting/DurationMeasuringPluginVerificationTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/mocks/MockTaskResult.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/mocks/SimpleTaskResultPrinter.kt
Show the total duration of plugin verification on console.
The console will show the following line in the final stage of verification process:
```
2023-10-02T12:40:47 [main] INFO  verification - Total time spent in plugin verification: 7 s 51 ms
```
> Show total duration of plugin verification in CLI

- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/deprecated/DeprecationUtil.kt
- intellij-plugin-verifier/verifier-test/after-idea/src/main/kotlin/deprecated/KotlinDeprecatedClass.kt
- intellij-plugin-verifier/verifier-test/before-idea/src/main/kotlin/deprecated/KotlinDeprecatedClass.kt
- intellij-plugin-verifier/verifier-test/mock-plugin/src/main/java/mock/plugin/deprecated/DeprecatedUser.java
Respect `DeprecationLevel.HIDDEN` in Kotlin @Deprecated annotation.
Do not treat such usages as deprecations.
Some libraries, e g. KotlinX Serialization, automatically inject such annotations into bytecode to manage internal processing.
The following usage is not considered to be a deprecation reported by the Plugin Verifier.
```
class KotlinDeprecatedClass() {
@Deprecated(message = "Use the default constructor", level = DeprecationLevel.HIDDEN)
constructor(x: Int) : this() {
// no-op
}
}
```
[See MP-6006](https://youtrack.jetbrains.com/issue/MP-6006) for further details.
> Respect DeprecationLevel.HIDDEN in Kotlin @Deprecated annotation

- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/jdk/JdkDescriptorCreator.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/jdk/JdkJImageResolver.kt
Simplify `jrt://` filesystem handling when reading JDK internals.
Rationale:
- Consolidate different modes of usage to [`newFilesystem`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/file/FileSystems.html#newFileSystem(java.nio.file.Path,java.util.Map)) call
- Call to `getFilesystem` is not handling a scenario where JDK image has been created from different `JAVA_HOME` than the default one
- Usage of `classloader` is not necessary. This mechanism is used to discover nonstandard URL schemas, but `jrt://` is a default one. In addition, class loader is no longer used as a closeable resource.
- Discovery of Java JDK location (_Java Home_) with `Home/Contents` structure is consolidated into a single place on MacOS.
See …
> Simplify JRT filesystem handling to make it compatible with JDK 17

- README.md
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/OptionsParser.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/ide/IdeDescriptor.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/jdk/JdkDescriptorProviders.kt
The CLI `-runtime-dir` switch is misleading.
Currently, 
```
The path to the directory containing Java runtime jar. If not specified, the JDK from 'JAVA_HOME' will be chosen.
```
However, this is not right and it prevents the non-default JDKs being properly used. In addition, testing plugins against IDEs and separate JDKs is impossible.
1. Use the `-runtime-dir` as a path to the JDK location (in the same spirit as `JAVA_HOME`). If this is not specified, then:
2. Discover JDK in the embedded IDE. If this is not available, then:
3. Fallback to `JAVA_HOME`.
See [MP-6028](https://youtrack.jetbrains.com/issue/MP-6028)
> Clarify `-runtime-dir` switch semantics

- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/reporting/telemetry/TelemetryAggregator.kt
The `TelemetryAggregator` is used by multiple threads.
Specifically, the `com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage` is used in multiple threads by the [`runSeveralVerifiers()`](https://github.com/JetBrains/intellij-plugin-verifier/blob/b27974bc34ff2f57db31d72b4a29389accda21fe/intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/PluginVerifierRun.kt#L35).
The underlying map has been made thread-safe. Note that the [`merge`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/ConcurrentHashMap.html#merge(K,V,java.util.function.BiFunction)) on the `ConcurrentHashMap` operation is handled atomically.
> Make telemetry aggregator thread-safe

- gradle/libs.versions.toml
- intellij-plugin-structure/structure-classes/build.gradle.kts
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/CacheResolver.kt
- intellij-plugin-verifier/verifier-core/build.gradle.kts
- intellij-plugin-verifier/verifier-core/src/main/java/com/jetbrains/pluginverifier/verifiers/method/KotlinMethods.kt
- intellij-plugin-verifier/verifier-repository/build.gradle.kts
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/ide/repositories/AndroidStudioIdeRepository.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/ide/repositories/IntelliJIdeRepository.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/ide/repositories/ReleaseIdeRepository.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/misc/HtmlBuilder.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/misc/HtmlEscaper.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/misc/RestApis.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/network/ThreadFactories.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/repository/cache/Memoizer.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/repository/repositories/custom/CustomPluginRepository.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/repository/repositories/marketplace/MarketplaceRepository.kt
Remove Guava dependency.
This will remove ~2MB from the CLI JAR file size.
- Use [Caffeine](https://github.com/ben-manes/caffeine) instead of Guava Caching
- Use custom HTML4.0 escaping implementation, taken and simplified from [`commons-text`](https://commons.apache.org/proper/commons-text/)
- Use custom implementation of `ThreadFactoryBuilder` instead of Guava
> Remove Guava dependency

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/LevelRemappingPluginCreationResultResolver.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/PluginCreationResultResolver.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/RemappedPluginProblems.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/ExistingPluginValidationTest.kt
Some plugin problems need to be ignored. An example issue is [MP-5911](https://youtrack.jetbrains.com/issue/MP-5911) _Not expected plugin verifier warning for plugin ID containing `intellij`_.
- Adjust `LevelRemappingPluginCreationResultResolver` to support _ignoring_ of specific plugin problems
- Improve syntax on various modes of level remapping.
- Add unit tests for various combinations of remapped plugin problems.
- Simplify remapping levels of plugin problem collections
- Remove ability to classify a single plugin problem as it is not used anywhere.
> Enable ignoring of specific plugin problems

- .github/dependabot.yml
- README_DEV.md
- intellij-plugin-verifier/README.md
- plugins-verifier-service/README.md
_Plugin Verifier Service_ has been replaced by a different implementation.
- Mark references in READMEs as deprecated
- Remove Dependabot monitoring
> Deprecate Plugin Verifier Service

- gradle/libs.versions.toml
- intellij-plugin-structure/build.gradle.kts
- intellij-plugin-verifier/build.gradle.kts
Enable publication of `intellij-plugin-verifier` to Maven Central.
- Improve Gradle build process
- Add signing via Gradle plugin
- Add publishing to Maven Central via Gradle plugin
> Publish intellij-plugin-verifier to Maven Central

- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/OptionsParser.kt
- Use thread-safe date and time formatting
- Improve copywriting on log message
> Improve copywriting and thread safety on verification directory retrieval in CLI

- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/output/markdown/MarkdownResultPrinter.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/output/stream/WriterResultPrinter.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/dymamic/DynamicPlugins.kt
- Use separate category for restrictions
- Explicitly emit a list of violated restrictions
- Address both plain text CLI and Markdown output
Sample stdout/CLI output:
```
Deprecated API usages (1): 
#Deprecated method com.intellij.ide.ApplicationInitializedListener.componentsInitialized() is overridden
Deprecated method com.intellij.ide.ApplicationInitializedListener.componentsInitialized() : void is overridden in class com.github.novotnyr.nondynamic.MyApplicationInitializedListener
Dynamic Plugin Eligibility (negative due to 2 restrictions):
Plugin probably cannot be enabled or disabled without IDE restart
#It declares non-dynamic extensions: `com.intellij.applicationInitializedListener`
#It declares a group without 'id' specified
```
> Improve presentation of dynamic status of a plugin in CLI

- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/twoTargets/TwoTargetsResultPrinter.kt
Improve copywriting on TeamCity messages
- Document that a Pull Request in a fork is usually necessary.
- Emphasize that API should be marked as deprecated before it is documented as an incompatible change.
> Improve documentation when documenting incompatible API changes

- README.md
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkTrunkApi/CheckTrunkApiParamsBuilder.kt
In `check-trunk-api` command, remove `--major-ide-version` (-miv) CLI switch.
It has not been used anywhere since major refactoring in 2017.
There are no requirements to use it, nor there were any complaints, until recently.
The alternative is to use `--major-ide-path` with a path to the IDE in the local filesystem.
See [MP-6080](https://youtrack.jetbrains.com/issue/MP-6080).
> check-trunk-api:  Remove --major-ide-version (-miv) CLI switch

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/InvalidDescriptorErrors.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/InvalidPluginsTest.kt
In the plugin descriptor, the `<since-build>` should not contain a wildcard. 
See [corresponding documentation in the IntelliJ Platform Plugin SDK](https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#build-number-validity).
I am adding this as a _warning_, later to be elevated to _error_.
> Value in <since-build> in plugin descriptor should not contain a wildcard

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/LevelRemappingPluginCreationResultResolver.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/RemappedPluginProblems.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/ExistingPluginValidationTest.kt
Support remapping any plugin problem to _error_ level.
Such remapping might change a successful plugin construction result from _successful_ to _failed_ status.
A specific plugin problem might be originally a _warning_, which corresponds to a successful construction, but remapping such issue to an _error_ will lead to a _construction failure_.
> Support remapping plugin problem to ERROR level

- intellij-plugin-verifier/build.gradle.kts
Create a Gradle task to emit release notes as a Markdown file.
Release notes are taken from the most recent released version in the `CHANGELOG.md`.
[Gradle Changelog Plugin](https://github.com/JetBrains/gradle-changelog-plugin) writes the changelog into stdout.
On GitHub Actions, this is captured into an environment variable.
Then, it is used to create _release notes_ for the corresponding GitHub release.
In TeamCity, this is not feasible due to technical reasons and build scripts.
Hence, we will write the most recent Changelog into a Markdown file in the `build` directory.
In the subsequent TeamCity build steps,
this file is picked up and used as a Release Notes document used in the GitHub release.
We are extending an `BaseChangelogTask` task from Gradle Changelog Plugin, applying …
> Create a Gradle task to emit the release notes

- intellij-plugin-structure/structure-fleet/src/main/kotlin/com/jetbrains/plugin/structure/fleet/FleetPlugin.kt
- intellij-plugin-structure/structure-fleet/src/main/kotlin/com/jetbrains/plugin/structure/fleet/FleetPluginDescriptor.kt
- intellij-plugin-structure/structure-fleet/src/main/kotlin/com/jetbrains/plugin/structure/fleet/FleetPluginManager.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/fleet/mock/FleetPluginMockTest.kt
- intellij-plugin-structure/tests/src/test/resources/fleet/extension.json
https://youtrack.jetbrains.com/issue/MP-6362/Support-frontend-only-flag-for-fleet-plugins
> Add frontend-only field for fleet plugins

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/problems/PluginProblems.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/IdePluginManager.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/InvalidPlugin.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/JetBrainsPluginCreationResultResolver.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/LevelRemappingPluginCreationResultResolver.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/ProblemLevelRemappingManager.kt
- intellij-plugin-structure/structure-intellij/src/main/resources/com/jetbrains/plugin/structure/intellij/problems/plugin-problems.json
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/problems/JsonUrlProblemLevelRemappingManagerTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/problems/LevelRemappingPluginCreationResultResolverTest.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/PluginParsingConfigurationResolution.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/options/PluginParsingConfigurationResolutionTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/ExistingPluginValidationTest.kt
- Fix case when reclassified plugin problem level might not be used properly, leading to a plugin descriptor discovery issue. 
- Unwrap plugin problem which have reclassified problem level.
- Introduce a special case of _invalid plugin_ which contains seemingly invalid plugin descriptor data. In some scenarios, even plugin with core plugin errors might be treated as valid due to relaxed rules. This is often a case with JetBrains plugins.
Before this improvement, a Plugin creation result resolver was not able to reclassify such basic validation problems.
- Introduce a set of plugin problem remappings for JetBrains plugins.
See [MP-6388](https://youtrack.jetbrains.com/issue/MP-6388)
> Rework plugin problem level remapping when reclassifying structural plugin descriptor problems

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/problems/PluginProblems.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/output/markdown/MarkdownResultPrinter.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/output/stream/WriterResultPrinter.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/InvalidPluginFile.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/output/markdown/MarkdownOutputTest.kt
In stdout output, distinguish between errors and other plugin problems:
```
The following files specified for the verification are not valid plugins:
/opt/my-plugin.jar
Plugin problems:
Invalid plugin descriptor 'plugin.xml'. The plugin id should not contain the word 'intellij'.
Additional plugin warnings:
Invalid plugin descriptor 'plugin.xml'. Multiple dependencies (4) use the same config-file attribute value 'plugin-apexdoc-lightweight.xml': [com.jetbrains.php, com.intellij.modules.python, com.intellij.modules.ruby, com.intellij.modules.webstorm].
```
Markdown:
```
The following file specified for the verification is not a valid plugin.
Full path: `plugin.zip`
* Invalid plugin descriptor 'plugin.xml'. The <since-build> parameter (1) format is invalid. Ensure it is greater than <130> …
```
> Distinguish errors and other plugin problems in Markdown and Console outputs

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/IdePluginImpl.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/StructurallyValidated.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/output/html/HtmlResultPrinter.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/plugin/PluginDetailsProvider.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/plugin/PluginDetailsProviderImpl.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/output/BaseOutputTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/output/stream/StreamOutputTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/dependencies/IdeDependencyFinderTest.kt
Pass structure warnings and structure unacceptable warnings to the verification reports.
This will show warnings in all outputs (HTML, Markdown, stdout).
For example:
```
Plugin com.github.novotnyr.plugin-service-preloading:1.0-SNAPSHOT against IE-203.7717.75: Compatible. 2 plugin configuration defects
Plugin structure warnings (2): 
Invalid plugin descriptor 'plugin.xml'. The change-notes parameter contains the default value 'Add change notes here' or 'most HTML tags may be used'.
Service preloading is deprecated in the <com.intellij.applicationService> element. Remove the 'preload' attribute and migrate to listeners, see https://plugins.jetbrains.com/docs/intellij/plugin-listeners.html.
Dynamic Plugin Eligibility:
Plugin can probably be enabled or disabled without IDE restart
```
See …
> Pass structure warnings to verification reports

- intellij-plugin-verifier/verifier-core/src/main/java/com/jetbrains/pluginverifier/verifiers/resolution/Methods.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/overrideOnly/BridgeMethodOverrideUsageFilter.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/overrideOnly/OverrideOnlyMethodUsageProcessor.kt
- intellij-plugin-verifier/verifier-test/after-idea/src/main/java/com/intellij/util/indexing/DataIndexer.java
- intellij-plugin-verifier/verifier-test/after-idea/src/main/java/com/intellij/util/indexing/FileBasedIndexExtension.java
- intellij-plugin-verifier/verifier-test/after-idea/src/main/java/com/intellij/util/indexing/FileContent.java
- intellij-plugin-verifier/verifier-test/after-idea/src/main/java/com/intellij/util/indexing/IndexExtension.java
- intellij-plugin-verifier/verifier-test/after-idea/src/main/java/com/intellij/util/indexing/IndexId.java
- intellij-plugin-verifier/verifier-test/after-idea/src/main/java/com/intellij/util/indexing/SingleEntryFileBasedIndexExtension.java
- intellij-plugin-verifier/verifier-test/after-idea/src/main/java/com/intellij/util/indexing/SingleEntryIndexer.java
- intellij-plugin-verifier/verifier-test/before-idea/src/main/java/com/intellij/util/indexing/DataIndexer.java
- intellij-plugin-verifier/verifier-test/before-idea/src/main/java/com/intellij/util/indexing/FileBasedIndexExtension.java
- intellij-plugin-verifier/verifier-test/before-idea/src/main/java/com/intellij/util/indexing/FileContent.java
- intellij-plugin-verifier/verifier-test/before-idea/src/main/java/com/intellij/util/indexing/IndexExtension.java
- intellij-plugin-verifier/verifier-test/before-idea/src/main/java/com/intellij/util/indexing/IndexId.java
- intellij-plugin-verifier/verifier-test/before-idea/src/main/java/com/intellij/util/indexing/SingleEntryFileBasedIndexExtension.java
- intellij-plugin-verifier/verifier-test/before-idea/src/main/java/com/intellij/util/indexing/SingleEntryIndexer.java
- intellij-plugin-verifier/verifier-test/mock-plugin/src/main/java/mock/plugin/overrideOnly/AbstractFileIndex.java
- intellij-plugin-verifier/verifier-test/mock-plugin/src/main/java/mock/plugin/overrideOnly/covariant/Child.java
- intellij-plugin-verifier/verifier-test/mock-plugin/src/main/java/mock/plugin/overrideOnly/covariant/ChildResult.java
- intellij-plugin-verifier/verifier-test/mock-plugin/src/main/java/mock/plugin/overrideOnly/covariant/Parent.java
- intellij-plugin-verifier/verifier-test/mock-plugin/src/main/java/mock/plugin/overrideOnly/covariant/ParentResult.java
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/verifiers/resolution/MethodsTest.kt
- Recognize covariant return types when detecting method overrides. For example, remember that `String foo()` might override `Object foo()` where `String extends Object`.
- Recognize synthetic [bridge methods](http://www.angelikalanger.com/GenericsFAQ/FAQSections/TechnicalDetails.html#FAQ103) when enumerating class methods. Bridge method is allowed to call an `@OverrideOnly` method, as it is a technical method to handle inheritance and generics.
- Reorganize method helper functions which detect overrides.
- Fix false positive in the Plugin Verifier that is connected with indexes.
See [MP-6438](https://youtrack.jetbrains.com/issue/MP-6438)
> Recognize covariant return types when detecting method overrides

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/MinorWarnings.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/verifiers/PluginIdVerifier.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/verifiers/PluginIdVerifierTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/InvalidPluginsTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/options/PluginParsingConfigurationResolutionTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/output/BaseOutputTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/output/markdown/MarkdownOutputTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/output/stream/StreamOutputTest.kt
- Fix unit tests for `ForbiddenPluginIdPrefix` which confuse plugin descriptor with plugin ID
- Pass plugin ID / plugin name in the plugin problem with disallowed words
- Improve copywriting
> Plugin ID and plugin name property fixes

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/problems/InvalidDescriptorErrors.kt
- intellij-plugin-structure/structure-fleet/src/main/kotlin/com/jetbrains/plugin/structure/fleet/FleetPluginDescriptor.kt
- intellij-plugin-structure/structure-toolbox/src/main/kotlin/com/jetbrains/plugin/structure/toolbox/ToolboxPluginDescriptor.kt
- intellij-plugin-structure/structure-youtrack/build.gradle.kts
- intellij-plugin-structure/structure-youtrack/src/main/kotlin/com/jetbrains/plugin/structure/youtrack/Validator.kt
- intellij-plugin-structure/structure-youtrack/src/main/kotlin/com/jetbrains/plugin/structure/youtrack/YouTrackVersionUtils.kt
- intellij-plugin-structure/structure-youtrack/src/main/kotlin/com/jetbrains/plugin/structure/youtrack/bean/YouTrackAppFields.kt
- intellij-plugin-structure/structure-youtrack/src/main/kotlin/com/jetbrains/plugin/structure/youtrack/bean/YouTrackAppManifest.kt
- intellij-plugin-structure/structure-youtrack/src/main/kotlin/com/jetbrains/plugin/structure/youtrack/problems/YouTrackPluginErrors.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/fleet/mock/FleetInvalidPluginsTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/toolbox/mock/ToolboxInvalidPluginsTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/youtrack/mock/YouTrackInvalidPluginTest.kt
In the branch, I moved semver validation errors from `fleet` and `toolbox` packages to `base` and reused them for `youtrack` version validation. Also, the method to get `long` from the YouTube version was added.
> YouTrack compatibility

- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/layout/ModuleFactory.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/dependencies/IdeDependencyFinderTest.kt
When creating dependency graph, resolve modules in the 2024.2.
Treat `IdeModule` as a plugin that treats itself as a module, in the same vein as if it was declared in the `<module>` element in the descriptor.
This fixes reports of failed module/plugin resolutions in the dependency report, such as:
```
(failed) module intellij.platform.vcs.impl: Plugins declaring module 'intellij.platform.vcs.impl' are not found in JetBrains Marketplace https://plugins.jetbrains.com
| +--- (optional) com.intellij.java:242.19533.56
```
This resolves the situation in the `BundledPluginsRepository` which discovers plugin by the module ID (`findPluginByModule`). Since many bundled plugins now pose as platform modules, the bundled plugin that is both module and a plugin is now discovered with the same algorithm …
> Dependency graph resolves modules in the 2024.2 layout

- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/annotation/AnnotationResolver.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/experimental/ExperimentalApiUsage.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/experimental/ExperimentalApiUsageProcessor.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/experimental/ExperimentalMethodOverridingProcessor.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/internal/InternalApiUsage.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/internal/InternalApiUsageProcessor.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/internal/InternalMethodOverridingProcessor.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/overrideOnly/OverrideOnlyMethodUsageProcessor.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/util/AnnotatedMemberUtil.kt
Log call stack including API element locations when tracking API usage of elements with:
- internal annotations
- experimental annotations
This allows to debug log the class/method/field locations including the corresponding JARs and directories.
It helps to address scenarios as split package declarations of multiple `package-info` or classpath resources that are scattered across multiple independent JARs.
> Log call stack when tracing annotation usage

- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/ProductInfoBasedIdeManager.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/platform/BundledModulesResolver.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/MockRiderBuilder.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/ProductInfoBasedIdeManagerTest.kt
This fix addresses an issue where the Plugin Verifier cannot resolve `com.intellij.modules.rider` modules in the Rider IDE.
In the Platform 2024.2+ layout, the Product Prefix was not properly resolved when using non-IDEA IDEs. This prefix is used to discover and resolve one of the Core Plugin descriptors.
For example, for JetBrains Rider, the Core Plugin descriptor resides in `lib/app.jar!META-INF/RiderPlugin.xml`, where `Rider` is derived from the Product Prefix.
This PR will extract the Product Prefix from the `product-info.json` and use it to correctly resolve the descriptor for the Core Plugin.
See [MP-6707](https://youtrack.jetbrains.com/issue/MP-6707)
See [PY-73342](https://youtrack.jetbrains.com/issue/PY-73342/Plugins-Compatibility-Check-com.github.copilot1.5.7.5758-Package-com.jetb …
> Unresolved com.intellij.modules.rider in the Rider IDE

- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/overrideOnly/DelegateCallOnOverrideOnlyUsageFilter.kt
`DelegateCallOnOverrideOnlyUsageFilter` that checks for delegate calls on methods with `@OverrideOnly` might fail when a delegate is `super`.
Filter out such method calls immediately, as `SuperclassCallOnOverrideOnlyUsageFilter` might be applied only in the later stages of API usage filtering.
See [MP-6724](https://youtrack.jetbrains.com/issue/MP-6724) Plugin Verifier: NPE on delegate calls in OverrideOnly Checks
> Fix NPE on delegate calls in OverrideOnly checks

- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/overrideOnly/DelegateCallOnOverrideOnlyUsageFilter.kt
`DelegateCallOnOverrideOnlyUsageFilter` that checks for delegate calls on methods with `@OverrideOnly` might fail when there is a similar method invocation, but with `static` modifier.
Invoking `static` methods with `@OverrideOnly` is contraintuitive as this leads to method shadowing.
See [MP-6724](https://youtrack.jetbrains.com/issue/MP-6724)
> Fix NPE on static delegate calls in OverrideOnly checks

- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/ClassLocationApiUsageFilter.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/SameOriginApiUsageFilter.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/SamePluginUsageFilter.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/experimental/ExperimentalApiUsageProcessor.kt
- intellij-plugin-verifier/verifier-test/after-idea/src/main/java/com/intellij/lang/jvm/JvmModifiersOwner.java
- intellij-plugin-verifier/verifier-test/after-idea/src/main/java/com/intellij/lang/jvm/JvmParameter.java
- intellij-plugin-verifier/verifier-test/after-idea/src/main/java/com/intellij/lang/jvm/package-info.java
- intellij-plugin-verifier/verifier-test/before-idea/src/main/java/com/intellij/lang/jvm/JvmModifiersOwner.java
- intellij-plugin-verifier/verifier-test/before-idea/src/main/java/com/intellij/lang/jvm/JvmParameter.java
- intellij-plugin-verifier/verifier-test/before-idea/src/main/java/com/intellij/lang/jvm/package-info.java
- intellij-plugin-verifier/verifier-test/mock-plugin/src/main/java/mock/plugin/platform/JvmParameterUsage.java
Use simple condition for the same-JAR API Usage verifications. 
This condition is picked up from the previous implementation where it expects that both the API host ("invocation target") and the API usage ("call-site") reside in the same JAR or directory.
This is a fix for issue where even the Platform-to-Platform internal APi calls with `@Experimental` API status might be wrongly reported as cross-plugin call.
See [MP-6729](https://youtrack.jetbrains.com/issue/MP-6729)
> Use simple condition for the same-JAR API Usage verifications

- README.md
Document format of the lines with optional fields.
> Improve documentation for `-ignored-problems` CLI switch

- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/overrideOnly/DelegateCallOnOverrideOnlyUsageFilter.kt
- intellij-plugin-verifier/verifier-test/mock-plugin/src/main/java/mock/plugin/overrideOnly/ClearCountingContainer.java
- intellij-plugin-verifier/verifier-test/mock-plugin/src/main/java/mock/plugin/overrideOnly/ClearCountingVector.java
- intellij-plugin-verifier/verifier-test/mock-plugin/src/main/java/mock/plugin/overrideOnly/Container.java
- intellij-plugin-verifier/verifier-test/mock-plugin/src/main/java/mock/plugin/overrideOnly/PackageInvokingBox.java
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/mocks/MockVerificationContext.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/usages/overrideOnly/DelegateCallOnOverrideOnlyUsageFilterTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/usages/overrideOnly/Dumps.kt
Add unit tests for cornercases:
- static method invocation: when a method invokes a `static` method with exactly the same name and exactly the same descriptor on another class
- `super` method invocation: when a method just plainly invokes a parent method
See #1111 and #1112
> Add unit test for `OverrideOnly` checks

- intellij-plugin-structure/structure-ide-classes/src/main/java/com/jetbrains/plugin/structure/ide/classes/IdeFileOrigin.kt
- intellij-plugin-structure/structure-intellij-classes/build.gradle.kts
- intellij-plugin-structure/structure-intellij-classes/src/main/java/com/jetbrains/plugin/structure/intellij/classes/locator/FileOriginProvider.kt
- intellij-plugin-structure/structure-intellij-classes/src/main/java/com/jetbrains/plugin/structure/intellij/classes/locator/JarPluginLocator.kt
- intellij-plugin-structure/structure-intellij-classes/src/main/java/com/jetbrains/plugin/structure/intellij/classes/locator/LibDirectoryLocator.kt
- intellij-plugin-structure/structure-intellij-classes/src/main/java/com/jetbrains/plugin/structure/intellij/classes/plugin/BundledPluginClassesFinder.kt
- intellij-plugin-structure/structure-intellij-classes/src/main/java/com/jetbrains/plugin/structure/intellij/classes/plugin/IdePluginClassesFinder.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/PluginVerifierMain.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/PluginVerifier.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/filtering/MainClassesSelector.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/resolution/BundledPluginClassResolverProvider.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/resolution/DefaultClassResolverProvider.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/SameOriginApiUsageFilter.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/SamePluginUsageFilter.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/experimental/ExperimentalApiUsageProcessor.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/javaPlugin/JavaPluginApiUsageProcessor.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/plugin/AbstractPluginDetailsProvider.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/plugin/DefaultPluginDetailsProvider.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/plugin/PluginDetailsProviderImpl.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/VerificationRunner.kt
- plugins-verifier-service/src/main/kotlin/org/jetbrains/plugins/verifier/service/server/configuration/ServerContextConfiguration.kt
Set proper `FileOrigin`s for bundled plugins.
Bundled plugin classes have been incorrectly marked as `FileOrigin` where they should have been more specifically: as an instance of `IdeFileOrigin`. This resolves multiple tricky corner-cases where class origins are not reported correctly as a part of the Platform.
This is an extension of #1120.
- Introduce `BundledPlugin` as a `FileOrigin`. This corresponds to an origin of classes that belong to the same bundled plugin. This helps to discriminate between class origins in the verification rules, especially those that detect Platform invocations from Plugin invocations.
- Allow customizable file origin resolution for JARs and `lib` directories. These have been originally set to `SingleJar` or `SingleLib`. Treating regular plugins and bundled …
> Set proper File Origins for bundled plugins

- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/ProductInfoBasedIdeManager.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/layout/PluginWithArtifactPathResult.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/MockIdeBuilder.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/ProductInfoBasedIdeManagerTest.kt
When constructing bundled plugins in the Platform 2024.2+ layout, the plugin problems should be properly remapped.
Otherwise, some bundled plugins cannot be loaded.
- Use the relaxed set of plugin problem verification that is used for JetBrains plugins.
- Apply them in the `ProductInfoBasedIdeManager` that is responsible for the Platform 2024.2+ layout.
- Resolve the `cwm-plugin` that is not being able to be loaded.
- Add it as a unit test sample.
- Improve debug logging on bundled plugins that cannot be loaded.
See [MP-6757](https://youtrack.jetbrains.com/issue/MP-6757) and [IJPL-158170](https://youtrack.jetbrains.com/issue/IJPL-158170).
> Remap bundled plugin problems when using Platform 2024.2+ layout

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/platform/ProductInfo.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/MockIdeBuilder.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/ProductInfoBasedIdeManagerTest.kt
- Make `versionSuffix` attribute is optional in `product-info.json`.
- Improve unit test infrastructure to support configurable mock Product Info variants.
See [MP-6774](https://youtrack.jetbrains.com/issue/MP-6774) Plugin Verifier: NPE on versionSuffix in Product Info JSON
> Make `versionSuffix` attribute optional in `product-info.json`

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/UnacceptableWarnings.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/verifiers/ExtensionPointVerifiers.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/verifiers/BaseExtensionPointTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/verifiers/LanguageBundleEpVerifierTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/verifiers/ServiceExtensionPointPreloadVerifierTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/verifiers/StatusBarWidgetFactoryExtensionPointVerifierTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/Extensions.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/SimpleProblemRegistrar.kt
As per docs, 
> com.intellij.languageBundle EP is internal and must be used by JetBrains only.
- Add a verifier for this verification rule.
- Add a new problem with _unacceptable warning_ severity.
- Consolidate common behaviours in the unit tests into a parent class.
See [MP-6788](https://youtrack.jetbrains.com/issue/MP-6788)
> Verify that `com.intellij.languageBundle` EP is internal and must be used by JetBrains only

- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/ProductInfoBasedIdeManager.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/dependencies/resolution/RepositoryDependencyFinder.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/plugin/AbstractPluginDetailsProvider.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/plugin/DefaultPluginDetailsProvider.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/plugin/SizeLimitedPluginDetailsCache.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/repository/WithIdePlugin.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/repository/repositories/bundled/BundledPluginInfo.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/repository/repositories/dependency/DependencyPluginInfo.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/repository/repositories/dependency/DependencyPluginRepository.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/repository/repositories/local/LocalPluginInfo.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/plugin/resolution/DependencyDiscoveryTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/plugin/resolution/InMemoryPluginFileProvider.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/plugin/resolution/InMemoryPluginFileProviderTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/plugin/resolution/InMemoryPluginRepository.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/plugin/resolution/Resolutions.kt
Plugin dependencies that are resolved as standard Platform plugins might contain problems. 
Some plugins, including those from JetBrains, may have problems leading to error-level plugin problems. In such cases, these plugins are not resolved as dependencies, which can result in unexpected reports of missing dependencies, even when they are actually available.
- Introduce a new `PluginInfo` type: `DependencyPluginInfo` that wraps any other plugin info. This indicates a plugin that will be resolved as a dependency.
- Introduce a repository that delegates to other repositories and treats the results as `DependencyPluginInfo` instances.
- Make corresponding `PluginInfo` instances aware of the `IdePlugin` via explicit interface when appropriate
- `AbstractPluginDetailsProvider` allows to …
> Remap plugin problems when resolving plugin dependencies

- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/verifiers/PluginVerificationContext.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/KotlinInternalModifierUsageTest.kt
Disable API usage checks of Kotlin `internal` modifier.
Rationale: The current implementation triggers many false positives, such as [MP-6784](https://youtrack.jetbrains.com/issue/MP-6784). Additional effort is required, with a scope extending beyond the 2024.2 release.
> Disable Kotlin `internal` modifier usage check

- intellij-plugin-structure/structure-intellij-classes/src/main/java/com/jetbrains/plugin/structure/intellij/classes/locator/LibModulesDirectoryLocator.kt
- intellij-plugin-structure/structure-intellij-classes/src/main/java/com/jetbrains/plugin/structure/intellij/classes/plugin/IdePluginClassesFinder.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/PluginClasspathTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/mocks/PluginDescriptors.kt
When resolving plugin classes in a ZIP or in a directory, discover classes in `lib/modules` JAR as well.
* Add a new `LibModulesDirectoryLocator` that searches for classes in the `lib/modules`
* Plug this locator into `IdeClassesFinder` default list of locators
See [MP-6799](https://youtrack.jetbrains.com/issue/MP-6799).
See also [IntelliJ Platform Gradle Plugin](https://github.com/JetBrains/intellij-platform-gradle-plugin/blob/10aa1af4016f710d5a2e2bf8cb4f877a0add3ba0/src/main/kotlin/org/jetbrains/intellij/platform/gradle/artifacts/transform/CollectorTransformer.kt#L89-L96) and its JAR handling in `lib/modules`.
> Discover plugin classes in `lib/modules` directory

- ide-diff-builder/src/main/java/org/jetbrains/ide/diff/builder/cli/ApiQualityCheckCommand.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/annotation/AnnotationResolver.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/experimental/ExperimentalApiUsage.kt
In `ide-diff-builder` migrate API usages in the `structure` library to the recent API.
> IDE Diff Builder: Migrate API usages in the structure library

- gradle/libs.versions.toml
Gradle Shadow plugin has been migrated to new coordinates. Now it resides at [GradleUp](https://gradleup.com/shadow/) with `com.gradleup.shadow`.
See https://github.com/GradleUp/shadow/releases/tag/8.3.0
> Upgrade Gradle Shadow plugin and change coordinates

- README.md
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/ProductDescriptor.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/InvalidDescriptorErrors.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/MinorWarnings.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/PluginCreationResultResolver.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/verifiers/ProductReleaseVersionVerifier.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/version/ProductReleaseVersion.kt
- intellij-plugin-structure/structure-intellij/src/main/resources/com/jetbrains/plugin/structure/intellij/problems/plugin-problems-cli-muteable.json
- intellij-plugin-structure/structure-intellij/src/main/resources/com/jetbrains/plugin/structure/intellij/problems/plugin-problems.json
- intellij-plugin-structure/structure-intellij/src/test/kotlin/com/jetbrains/plugin/structure/intellij/version/ProductReleaseVersionTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/PluginXmlValidationTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/problems/JsonUrlProblemLevelRemappingManagerTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/InvalidPluginsTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/MockPluginXml.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/MockPluginsTest.kt
- intellij-plugin-structure/tests/src/test/resources/mock-plugin/META-INF/plugin.xml
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/plugin/resolution/DependencyDiscoveryTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/ExistingPluginValidationTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/LevelRemappingTest.kt
[JetBrains Marketplace Guidelines](https://plugins.jetbrains.com/docs/marketplace/add-required-parameters.html) specify validation rules for `release-version` parameter that are applied on paid plugins.
New Plugin Problems
-------------------
1. `ReleaseVersionWrongFormat` when a `release-version` does not have two digits. This is an _error_ for new plugins and a _warning_ for existing plugins.
2. `ReleaseVersionAndPluginVersionMismatch` when a `release-version` does match the plugin version. This is an _error_ for both new plugins and existing plugins, and a _ignored_ problem for JetBrains plugins.
Technical improvements
----------------------
- Introduce `ProductReleaseVersionVerifier` as a separate class for `product-release` verification
- Introduce type-safe `ProductReleaseVersion` …
> Validate 'release-version' for paid plugins

- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/layout/PluginFactory.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/layout/PluginWithArtifactPathResult.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/IdePluginManager.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginFileNotFoundException.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/MockIdeBuilder.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/ProductInfoBasedIdeManagerTest.kt
Handle plugins created from malformed paths in `product-info.json`.
- Create a custom `PluginFileNotFoundException` and throw it instead of generic `IllegalArgumentException` when plugin artifact is not found
- When creating plugins from `product-info.json`, catch `PluginFileNotFoundException` and rewrap to `Failure` in the `ProductInfoBasedIdeManager`
- Improve logging in the `ProductInfoBasedIdeManager` when bundled plugins in the IDE cannot be created
This is a workaround for certain broken IDE releases, which contain nonsensical paths in publicly available SNAPSHOT releases.
See [MP-6920](https://youtrack.jetbrains.com/issue/MP-6920)
> Handle plugins created from malformed paths in `product-info.json`

- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/PluginVerifier.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/results/problems/CompatibilityProblemResolver.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/results/problems/KotlinCompatibilityModeProblemResolver.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/results/problems/UndeclaredKotlinK2CompatibilityModeWarning.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/K2ModeCompatibilityTest.kt
Treat missing declaration of compatibility with K2 mode for Kotlin-dependent plugins is a warning.
Acording to clarification, the `org.jetbrains.kotlin.supportsKotlinPluginMode` is required to mark a plugin that has been already migrated to the K2 Kotlin Analysis API.
- Rename `UndeclaredKotlinK2CompatibilityModeProblem` to `UndeclaredKotlinK2CompatibilityModeWarning`. Make it inherit from `CompatibilityWarning` instead.
- Support resolution of `CompatibilityWarning`s from `PluginVerificationContext`.
- Migrate implementation from _problems_ to _warnings_ in the `CompatibilityProblemResolver`.
See also a base PR #1150.
> Missing declaration of compatibility with K2 mode for Kotlin-dependent plugins is a warning

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/verifiers/PluginIdVerifier.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/verifiers/PluginIdVerifierTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/IdePluginManagerTest.kt
Remove JetBrains vendor check from `PluginIdVerifier`.
This is a duplicate logic. Any `TemplateWordInPluginId` and `ForbiddenPluginIdPrefix` that are emitted from the `PluginIdVerifier` are already suppresed by the plugin problem remapping mechanism.
Any client library can customize this behaviour by using a proper `PluginCreationResultResolver`. For example, a `JetBrainsPluginCreationResultResolver` can wrap a `LevelRemappingPluginCreationResultResolver`. The latter can explicitly suppres both of these plugin problems.
> Remove JetBrains vendor check from `PluginIdVerifier`

- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/ProductInfoBasedIdeManager.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/layout/PluginWithArtifactPathResult.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/platform/ProductInfo.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/MockIdeBuilder.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/ProductInfoBasedIdeManagerTest.kt
Some distributions contain `product-info.json` with layout components that do not exist in the filesystem. 
For example, this is the layout entry:
```
{
"name": "org.jetbrains.plugins.emojipicker",
"kind": "plugin",
"classPath": [
"plugins/emojipicker/lib/emojipicker.jar"
]
}
```
However,  no `plugins/emojipicker/lib/emojipicker.jar` is available in the Windows distribution, as this plugin is Linux-only.
- Platform-wide `ResourceResolver` is pointing to invalid files which will break resource resolution. Especially, when a plugin is XIncluding another descriptor that should be present in such resolver, resolution in a nonexistent JAR file will throw an exception.
- Parsing of such layout elements might lead to nonexistent classpath.
- In platform-wide `ResourceResolver`, do not include …
> Do not resolve Product Info layout components without actual files in the distribution

- intellij-plugin-structure/structure-teamcity-actions/src/main/kotlin/com/jetbrains/plugin/structure/teamcity/action/TeamCityActionDescriptor.kt
- intellij-plugin-structure/structure-teamcity-actions/src/main/kotlin/com/jetbrains/plugin/structure/teamcity/action/TeamCityActionPluginManager.kt
- intellij-plugin-structure/structure-teamcity-actions/src/main/kotlin/com/jetbrains/plugin/structure/teamcity/action/TeamCityActionProblems.kt
- intellij-plugin-structure/structure-teamcity-actions/src/main/kotlin/com/jetbrains/plugin/structure/teamcity/action/TeamCityActionSpec.kt
- intellij-plugin-structure/structure-teamcity-actions/src/main/kotlin/com/jetbrains/plugin/structure/teamcity/action/TeamCityActionSpecVersionUtils.kt
- intellij-plugin-structure/structure-teamcity-actions/src/main/kotlin/com/jetbrains/plugin/structure/teamcity/action/Validator.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/teamcity/action/ParseInvalidActionTests.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/teamcity/action/ParseValidActionTests.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/teamcity/action/ParseValidFullActionTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/teamcity/action/TestData.kt
The specification version will no longer be stated explicitly in the action's YAML, but will be calculated explicitly at the moment of the upload. Currently, all uploaded actions will have the specification version 1.0.0. After we add new capabilities to actions, we will calculate the specification version based on the YAML content. I have discussed this with @kesarevs.
Unknown properties in the action's YAML will now fail the deserialization. This is used to protect us from incorrectly calculating the specification format version by not including unknown fields in the calculation.
> Remove the spec-version property from TeamCity Actions

- README.md
- intellij-plugin-structure/structure-ide-classes/src/main/java/com/jetbrains/plugin/structure/ide/classes/IdeResolverConfiguration.kt
- intellij-plugin-structure/structure-ide-classes/src/main/java/com/jetbrains/plugin/structure/ide/classes/IdeResolverCreator.kt
- intellij-plugin-structure/structure-ide-classes/src/main/java/com/jetbrains/plugin/structure/ide/classes/resolver/ProductInfoClassResolver.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/layout/IdeRelativePath.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/layout/InvalidIdeLayoutException.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/layout/LayoutComponents.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/layout/MissingLayoutFileMode.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/layout/ResolvedLayoutComponent.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/resolver/LayoutComponentsProvider.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/resolver/ProductInfoResourceResolver.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/classes/IdeResolverCreatorTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/classes/resolver/PluginDependencyFilteredResolverTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/plugin/dependencies/DependenciesTest.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/CmdOpts.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/OptionsParser.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/ide/IdeDescriptor.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/cli/OptionsParserTest.kt
In nightly versions of the Platform, the `product-info.json` contains layout components with `classpath` entries that do not exist in the filesystem. 
For example:
```
"layout": [
{
"name": "intellij.qodana.sarif",
"kind": "moduleV2",
"classPath": [
"plugins/qodana/lib/modules/intellij.qodana.sarif.jar"
]
}
]
```
- Consolidate logic resolution for both `ResourceResolver` and `Resolver` in the Structure library.
- By default, when a such missing classpath entries occur, skip the whole layout component. Then, log accordingly at _warn_ level.
- Add a CLI parameter switch `-missing-layout-classpath-file` to configure behavior from the command line.
> Consolidate resolution logic for missing layout component files

- gradle/libs.versions.toml
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/ProductInfoBasedIdeManager.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/layout/LayoutComponents.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/layout/MissingLayoutFileMode.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/resolver/LayoutComponentsProvider.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/resolver/ProductInfoResourceResolver.kt
- intellij-plugin-structure/tests/build.gradle.kts
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/MockIdeBuilder.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/ProductInfoBasedIdeManagerTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/plugin/dependencies/DependenciesTest.kt
Support `product-info.json` in MacOS distributions, where the corresponding files are in the `Resources` subfolder.
> Support `product-info.json` in MacOS distributions

- intellij-plugin-verifier/verifier-core/src/main/java/com/jetbrains/pluginverifier/verifiers/filter/SameModuleUsageFilter.kt
- intellij-plugin-verifier/verifier-core/src/main/java/com/jetbrains/pluginverifier/verifiers/resolution/Methods.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/internal/InternalMethodOverridingProcessor.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/InternalApiUsagePluginTest.kt
Allow to override an _internal method_ of a class that belongs to the same plugin.
- [MP-7136 Plugin Verifier: Overriding a method with @Internal annotation within the same plugin](https://youtrack.jetbrains.com/issue/MP-7136)
> Overriding internal API in the same JAR

- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/DispatchingIdeManager.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/IdeManagers.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/ProductInfoBasedIdeManager.kt
- intellij-plugin-structure/structure-ide/src/test/kotlin/com/jetbrains/plugin/structure/ide/IdeManagersTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/plugin/dependencies/DependenciesTest.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/ide/IdeDescriptor.kt
When creating a generic IDE Manager, allow to provide a configuration.
A _missing layout file mode_ is currently enabled for configuration. This mode is propagated to the `DispatchingIdeManager` and the `ProductInfoBasedIdeManager` that supports this behaviour for Platform 2024.2 and newer.
This allows integration with [IntelliJ Platform Gradle Plugin](https://github.com/JetBrains/intellij-platform-gradle-plugin), when creating IDEs.
> Allow to configure `IdeManager` when layout components are missing

- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/IdeManagers.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/ProductInfoBasedIdeManager.kt
- intellij-plugin-structure/structure-ide/src/test/kotlin/com/jetbrains/plugin/structure/ide/IdeManagersTest.kt
- Make `DispatchingIdeManager` configurable with ability to provide mode for missing layout entries
- Establish an alternative API to create IDEs with configuration
- When creating IDE Descriptor, honor the configuration for the resolver and for the IDE as well.
> Make dispatching IDE Manager configurable

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/plugin/Settings.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/utils/FileUtil.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/base/plugin/SettingsTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/SimplePluginCreatorResultResolver.kt
Increase plugin artifact size limit to 1.5GB.
See [MP-7177](https://youtrack.jetbrains.com/issue/MP-7177/Increase-plugin-artifact-size-limit-to-1.5GB)
> Increase plugin artifact size limit to 1.5GB

- intellij-plugin-structure/structure-dotnet/src/main/kotlin/com/jetbrains/plugin/structure/dotnet/Validator.kt
- intellij-plugin-structure/structure-fleet/src/main/kotlin/com/jetbrains/plugin/structure/fleet/FleetPluginDescriptor.kt
- intellij-plugin-structure/structure-hub/src/main/kotlin/com/jetbrains/plugin/structure/hub/Validator.kt
- intellij-plugin-structure/structure-toolbox/src/main/kotlin/com/jetbrains/plugin/structure/toolbox/ToolboxPluginDescriptor.kt
- intellij-plugin-structure/structure-youtrack/src/main/kotlin/com/jetbrains/plugin/structure/youtrack/Validator.kt
- intellij-plugin-structure/structure-youtrack/src/main/kotlin/com/jetbrains/plugin/structure/youtrack/problems/YouTrackPluginErrors.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/dotnet/mock/DotNetPluginTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/hub/mock/HubInvalidPluginsTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/hub/mock/HubMockPluginBuilder.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/youtrack/mock/YouTrackInvalidPluginTest.kt
Validate plugin identifiers for Hub, YouTrack and .NET plugins. 
- For .NET and Hub: Allow alphanumeric characters, dash (`-`), dot `.`, underscore (`_`).
- For YouTrack: Allow lowercase alphanumeric characters, dash (`-`), dot `.`, underscore (`_`).
> Add validation for xml ids

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/Jars.kt
- intellij-plugin-structure/structure-ide/src/test/kotlin/com/jetbrains/plugin/structure/ide/traversal/PlatformSearcher.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/jar/SingletonCachingJarFileSystemProviderTest.kt
When a jar file was opened with different uris pointing to the same file they would return the same file system because the jdk normalizes the uri, eg jar:file:/tmp/../tmp/file.jar becomes jar:file:/tmp/file.jar.
Therefore the number of users of one filesystem was incorrect and it might have been closed while still in use.
This occured eg. in mono repos with multiple intellij plugins and parallel builds.
> Reuse filesystem accessed by different uri to the same file

- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/DispatchingIdeManager.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/IdeManagerImpl.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/ProductInfoBasedIdeManager.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/UndeclaredInLayoutPluginReader.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/layout/ModuleFactory.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/layout/ModuleLoadingContext.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/plugin/DefaultPluginIdProvider.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/plugin/MissingPluginIdException.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/plugin/PluginIdExtractor.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/xml/ElementNamesFilter.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/xml/ElementStack.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/xml/ElementTextContentFilter.kt
- intellij-plugin-structure/structure-ide/src/test/kotlin/com/jetbrains/plugin/structure/ide/plugin/PluginIdExtractorTests.kt
- intellij-plugin-structure/structure-ide/src/test/kotlin/com/jetbrains/plugin/structure/ide/plugin/PluginIdProviderTest.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/BundledPluginManager.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginArtifactPath.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginIdProvider.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/jar/PluginDescriptorProvider.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/MockIdeBuilder.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/ProductInfoBasedIdeManagerTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/plugin/BundledPluginManagerTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/PluginVerifierTelemetryTest.kt
Android Studio contains a plugin in the `plugins` folder that is not declared in the `product-info.json`.
- For explicitly enumerated product codes, traverse `plugins` folder. Discover plugins that are not declared in the Product Info and load them into the IDE.
- Introduce the `UndeclaredInLayoutPluginReader` that handles loading logic for undeclared plugins that will be loaded from `plugins` folder.
- Introduce a StAX-based parser of `plugin.xml` to quicky identify plugin identifiers without unnecessary parsing of the full plugin descriptor. See `ElementTextContentFilter` for filtering logic in StAX streams
Additional fixes:
- When a module descriptor refers to non-existent _resource root_, warn, and do not load the corresponding module.
See …
> Plugin Verifier cannot find org.jetbrains.android plugin

- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/DispatchingIdeManager.kt
Discover plugins that are not declared in the Product Info and load them into the IDE for CLion.
See [MP-7275](https://youtrack.jetbrains.com/issue/MP-7275) Structure: Resolve CLion bundled plugins undeclared in `product-info.json`.
See also #1214.
> Discover bundled plugins in 'plugins' directory in CLion

- ide-diff-builder/gradle/wrapper/gradle-wrapper.properties
- intellij-feature-extractor/build.gradle.kts
- intellij-feature-extractor/gradle/wrapper/gradle-wrapper.properties
- intellij-feature-extractor/gradlew
- intellij-feature-extractor/src/main/java/com/jetbrains/intellij/feature/extractor/extractor/FileTypeFactoryExtractor.kt
- intellij-plugin-structure/gradle/wrapper/gradle-wrapper.properties
- intellij-plugin-verifier/gradle/wrapper/gradle-wrapper.properties
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/bytecode/ByteCodeDescriptions.kt
- plugins-verifier-service/gradle/wrapper/gradle-wrapper.properties
- plugins-verifier-service/gradlew
- Upgrade to [Gradle 8.12.1](https://docs.gradle.org/8.12.1/release-notes.html).
- `intellij-feature-extractor`: align unit test and instruction detection logic to match modern compilers and JVM. Previously, it was thought that `NEWARRAY` was the only source of a new array on the operand stack in JVM. However, this array can be also accessed via `DUP` instruction what was not detected.
> Bump Gradle to 8.12.1 and align JVM bytecode logic

- CHANGELOG.md
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/utils/KtClassResolver.kt
- intellij-plugin-verifier/verifier-core/src/main/java/com/jetbrains/pluginverifier/verifiers/method/KotlinMethods.kt
Address OutOfMemoryIssues
- Use _Caffeine_ instead of plain ever-growing `HashMap`.
- Reorganize code for Kotlin `DefaultImpls`.
See [MP-6767](https://youtrack.jetbrains.com/issue/MP-6767)
> Improve performance in caches

- intellij-plugin-structure/structure-ide-classes/src/main/java/com/jetbrains/plugin/structure/ide/classes/resolver/PluginDependencyFilteredResolver.kt
- intellij-plugin-structure/structure-ide-classes/src/main/java/com/jetbrains/plugin/structure/ide/classes/resolver/ProductInfoClassResolver.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/classes/resolver/ProductInfoClassResolverTest.kt
- intellij-plugin-structure/tests/src/test/resources/ide/productInfo/product-info_mini.json
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/dependencies/DependenciesGraphBuilder.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/dependencies/resolution/BundledPluginDependencyFinder.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/dependencies/resolution/CompositeDependencyFinder.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/dependencies/resolution/DependencyFinder.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/dependencies/resolution/RepositoryDependencyFinder.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/resolution/DefaultClassResolverProvider.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/dependencies/resolution/CompositeDependencyFinderTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/BasePluginTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/dependencies/BundledModuleDependencyTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/dependencies/OptionalDependenciesTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/mocks/MockDependencyFinder.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/mocks/PluginBuilders.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/mocks/RuleBasedDependencyFinder.kt
A plugin might declare a dependency on a V1 plugin via V2 semantics.
```
<dependencies>
<plugin id="com.intellij.platform.ide.provisioner" />
</dependencies>       
````
However, such plugin isan alias of the Core plugin. Add support for such scenario when resolving classes.
In `ProductInfoClassResolver`, group all `productModuleV2` from the Product Info under a single logical `Resolver`. In addition, maintain the list of mappings between product layout entries and their actual resolvers.
Thus, `com.intellij.platform.ide.provisioner` maps to the `Resolver` of the Core plugin with the nested resolvers still being available by their corresponding IDs.
> Support module aliases in class resolvers when used as dependencies

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/MockPluginV2Test.kt
- intellij-plugin-structure/tests/src/test/resources/mock-plugin-v2/META-INF/plugin.xml
- intellij-plugin-structure/tests/src/test/resources/mock-plugin-v2/intellij.v2.module.xml
- intellij-plugin-structure/tests/src/test/resources/mock-plugin-v2/intellij.v2.required.module.xml
This pull requests addresses two problem with handling 'content' v2 modules:
* 'package' attribute is actually optional;
* if `required` (or `embedded`) loading rule is specified for a module, its dependencies must be treated as non-optional dependencies of the plugin.
> Refine requirements for v2 modules

- intellij-plugin-structure/structure-edu/src/main/kotlin/com/jetbrains/plugin/structure/edu/EduPlugin.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/edu/mock/EduPluginMockTest.kt
In order to store tasks names on the Markeplace side `EduStat` from `structure-edu` was altered and now holds both `task_type to count` map and `lesson name to tasks names` map
> Save tasks names in `EduStat`

- intellij-plugin-structure/structure-edu/src/main/kotlin/com/jetbrains/plugin/structure/edu/EduPlugin.kt
- intellij-plugin-structure/structure-edu/src/main/kotlin/com/jetbrains/plugin/structure/edu/bean/EduPluginDescriptor.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/edu/mock/EduPluginMockTest.kt
Is needed to allow changing the plugin descriptor and validate it without affecting the structure - MP communication.
> Split DTO and bean for Edu tasks field

- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/JarFileSystemsPool.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/IdeManagerImpl.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/JarFilesResourceResolver.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/resources/JarResourceResolverTest.kt
- Deprecate `JarFilesResourceResolver`
- Replace implementations with `JarsResourceResolver` in production code
- Deprecate `JarFileSystemsPool` as the internal implementation detail of `JarFilesResourceResolver`
> Deprecate `JarFilesResourceResolver`

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/CachingJarFileSystemProvider.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/PluginJar.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/SingletonCachingJarFileSystemProvider.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/ProductInfoBasedIdeManager.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/JarFilesResourceResolver.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/jar/CachingJarFileSystemProviderTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/jar/SingletonCachingJarFileSystemProviderTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/xinclude/XIncludes.kt
- Extract away the caching functionality to a separate class `CachingJarFileSystemProvider`. Remove the original implementation as it is used nowhere and has a better implementation now.
- Establish a 10 second retention time for cached entries. This prevents multiple consequent open-close operations that lead to unnecessary constructions and immediate closings of a specific filesystem.
- Do not log when no expirations will take place.
- Migrate all remaining production code to the `SingletonCachingJarFileSystemProvider` implementation.
> Improve caching in singleton JAR filesystem provider

- intellij-feature-extractor/src/test/java/com/intellij/featureExtractor/MockIdePlugin.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/IdePlugin.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/IdePluginImpl.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/InvalidPlugin.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/module/IdeModule.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/PluginXmlValidationTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/MockIdePlugin.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/MockPluginV2Test.kt
- intellij-plugin-structure/tests/src/test/resources/descriptors/ml-llm/plugin-single-module-in-cdata.xml
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/analysis/LegacyPluginAnalysis.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/dependencies/IdeDependencyFinderTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/mocks/MockIdePlugin.kt
This pull request fixes [MP-7413](https://youtrack.jetbrains.com/issue/MP-7413) and [MP-7414](https://youtrack.jetbrains.com/issue/MP-7414),  and also deprecates 'IdePlugin::isV2' property which may be confusing.
> fix false-positive 'No dependencies' error and deprecate confusing 'IdePlugin::isV2'

- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/CacheResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/CompositeResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/DirectoryResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/EmptyResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/FixedClassesResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/JarFileResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/LazyCompositeResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/LazyJarResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/PackageSet.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/Packages.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/Resolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/jar/Jar.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/utils/Trie.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/utils/TrieTraversals.kt
- intellij-plugin-structure/structure-ide-classes/src/main/java/com/jetbrains/plugin/structure/ide/classes/resolver/CachingPluginDependencyResolverProvider.kt
- intellij-plugin-structure/structure-ide-classes/src/main/java/com/jetbrains/plugin/structure/ide/classes/resolver/ProductInfoClassResolver.kt
- intellij-plugin-structure/structure-ide-classes/src/main/java/com/jetbrains/plugin/structure/ide/util/KnownIdePackages.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/classes/resolvers/PackagesTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/classes/utils/TrieTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/classes/IdeResolverCreatorTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/classes/resolver/CachingPluginDependencyResolverProviderTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/classes/resolver/ProductInfoClassResolverTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/MockPluginV2Test.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/MockPluginsTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/resolvers/ResolverTest.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/PluginVerifier.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/jdk/JdkJImageResolver.kt
The `Resolver` class has a `allPackages` property. This is very inefficient: when a `CompositeResolver` is rebuilding its internal cache, it launches a full-recursive resolver-tree traversal.
However, this property is used only in a single place: when tracking usage of known IDE packages in the plugin.
- Introduce a `Trie` property to track packages.
- Introduce a `Packages` class representing a package tree backed by the `Trie`. This is a more efficient counterpart to the `PackageSet`. 
- Deprecate `allPackages` property. Remove its usage in the production code. Replace the single actual usage with the `Packages` tracking.
> Deprecate 'allPackages' property on Resolver

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/PluginJar.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/module/ContentModuleScanner.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/base/utils/Zips.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/plugin/module/ContentModuleScannerTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/zipBombs/CorruptedZips.kt
A broken ZIP can fail the plugin verification. This is due to the unhandled exception when scanning for content modules via `PluginJar`.
- Rework `ContentModuleScanner` to handle such exceptions.
- Prepare test fixtures for broken ZIPs.
> Broken ZIP does not fail verification when scanning for content modules

- intellij-plugin-structure/structure-ide-classes/src/main/java/com/jetbrains/plugin/structure/ide/classes/resolver/CachingPluginDependencyResolverProvider.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/Classpath.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/IdePluginManager.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/classes/resolver/CachingPluginDependencyResolverProviderTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/PluginClasspathTest.kt
When creating a `classpath` for any plugin or module by content module scanning, remove duplicate classpath entries.
Every such duplicate entry produces a separate JarResolver, possibly consuming duplicate memory.
> Fix classpath duplicates

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/Jars.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/jar/JarsTest.kt
Remove duplicate `file` subschema from `URI`s.
Before, a path could have been resolved to `jar:file:file:///var/archive.jar`. Now, it is a correct absolute `jar:file:///var/archive.jar`.
This PR fixes the path resolution and adds unit tests.
> Remove duplicate 'file' subschema from URIs

- intellij-plugin-structure/structure-ide-classes/src/main/java/com/jetbrains/plugin/structure/ide/classes/resolver/ProductInfoClassResolver.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/classes/resolver/ProductInfoClassResolverTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/MockProductInfoAwareIde.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/mocks/MockProductInfoAwareIde.kt
- `ProductInfoClassResolver` might parse the `product-info.json` twice. If this type-safe `ProductInfo` is already present in the `Ide` instance, skip unnecessary duplicate parsing.
- Introduce `MockProductInfoAwareIde` both in _Structure_ and _Plugin Verifier_.
> Fix duplicate parsing of Product Info in class resolver

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/Names.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/utils/BinaryClasses.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/utils/CharSequenceComparator.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/CacheResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/CompositeResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/DirectoryResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/EmptyResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/FixedClassesResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/JarFileResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/LazyCompositeResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/LazyJarResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/Resolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/SimpleCompositeResolver.kt
- intellij-plugin-structure/structure-ide-classes/src/main/java/com/jetbrains/plugin/structure/ide/classes/resolver/CachingPluginDependencyResolverProvider.kt
- intellij-plugin-structure/structure-ide-classes/src/main/java/com/jetbrains/plugin/structure/ide/classes/resolver/ProductInfoClassResolver.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/classes/resolvers/jar/LazyJarResolverTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/classes/IdeResolverCreatorTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/classes/resolver/CachingPluginDependencyResolverProviderTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/MockPluginV2Test.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/MockPluginsTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/resolvers/ResolverTest.kt
- intellij-plugin-verifier/verifier-core/src/main/java/com/jetbrains/pluginverifier/verifiers/BytecodeVerifier.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/PluginVerifier.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/filtering/ClassesSelector.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/filtering/ExternalBuildClassesSelector.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/filtering/MainClassesSelector.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/jdk/JdkJImageResolver.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/PluginClasspathTest.kt
- Introduce `BinaryClassName` that explicitly indicates a class name separated by '/' as per [Java Virtual Machine Specification §4.2.1](https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-4.html#jvms-4.2.1).
- Enable `Resolver` to 
* resolve class by `BinaryClassName`: `resolveClass`
* detect if a class is present: `containsClass`
* list all available classes: `allClasses`
- Update production code and tests to use the new methods
- Deprecate `String`-based methods in `Resolver`.
This enables more effective JAR-based resolvers that base class names on byte arrays instead of Strings. Such resolvers might be more efficient and prevent unnecessary construction of Strings that require more heap.
> Introduce `BinaryClassName` as a type-safe variant to String

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/xml/XmlStreamEventFilter.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/xml/XmlStreamings.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/xml/XmlTransformationContext.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/dependencies/PluginXmlDependencyFilter.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/plugin/DefaultPluginIdProvider.kt
- intellij-plugin-structure/structure-ide/src/test/kotlin/com/jetbrains/plugin/structure/xml/DocumentTypeEventFilterTest.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/descriptors/IdeaPluginXmlDetector.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/descriptors/StaxIdeaPluginXmlDetector.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/module/ContentModuleScanner.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/base/utils/PluginJarDescriptorTest.kt
StAX [`XMLInputFactory`](https://docs.oracle.com/en/java/javase/17/docs/api/java.xml/javax/xml/stream/XMLInputFactory.html) and [`XMLOutputFactory`](https://docs.oracle.com/javase/8/docs/api/javax/xml/stream/XMLOutputFactory.html) are generally not thread-safe. However, it is unnecessary to create an instance with each call when parsing an XML document.
- Introduce `XmlInputFactoryResult` to hold hold a type-safe result for construction of `XMLInputFactory`.
- Introduce `XmlOutFactoryResult` as a parallel mechanism for output factories.
- Introduce `XmlTransformationContext` that holds both the XML input and output factory for transformations or fast XML parsing.
- Use these constructs
* When parsing plugin IDs from the plugin descriptors.
* When parsing plugin content modules
This …
> Reuse XML factory instances when parsing plugin identifiers and content modules

- .github/workflows/ide-diff-builder.yml
- .github/workflows/intellij-feature-extractor.yml
- .github/workflows/intellij-plugin-structure.yml
- .github/workflows/intellij-plugin-verifier.yml
- .github/workflows/plugins-verifier-service.yml
_Gradle Wrapper Validation_ has updated its coordinates. Change the coordinates to the new location and use the most recent version.
This eliminates the frequent connectivity issues, such as:
```
Run gradle/actions/wrapper-validation@v3.5.0
Error: Multiple errors returned
Error: Error 0: connect ETIMEDOUT 104.16.73.101:443
Error: connect ETIMEDOUT 104.16.73.101:443
at createConnectionError (node:net:1652:14)
at Timeout.internalConnectMultipleTimeout (node:net:17[11](https://github.com/JetBrains/intellij-plugin-verifier/actions/runs/14774280767/job/41479662518?pr=1262#step:3:13):38)
at listOnTimeout (node:internal/timers:583:11)
at process.processTimers (node:internal/timers:519:7)
Error: Error 1: connect ENETUNREACH 2606:4700::6810:4965:443 - Local (:::0)
Error: connect ENETUNREACH …
```
> Update coordinates of Gradle Wrapper Validation Action

- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/AbstractJarResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/InvalidClassFileException.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/utils/AsmUtil.java
Allow to read class nodes from ASM via binary class names. 
The binary class name serves a debugging / tracing purpose only. ASM library is able to deduce the class node name from the bytecode.
> Read ASM class nodes via binary class names

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/CachingJarFileSystemProvider.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/FsHandleFileSystem.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/Jar.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/JarFileSystemProvider.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/classes/resolvers/jar/JarTest.kt
When batch-processing classes in a `Resolver`, the underlying filesystem can be closed. Prevent such situations.
- Advice a total number of potential references to the caching JAR filesystem provider. For example, when a resolver has 3 classes, advice 3 usages which contribute to the reference count. This decreases the chance that the filesystem will be closed.
- Create a separate method in the `JarFileSystemProvider` with type-safe configuration. This is similar to the [FileSystems#newFileSystem(URI, Map)](https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystems.html#newFileSystem-java.net.URI-java.util.Map-) method in the Java SDK. Provide the number of expected clients in this configuration.
> Ensure filesystem remains open during class batch processing in an `Resolver`

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/CachingJarFileSystemProvider.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/Jar.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/classes/resolvers/jar/JarTest.kt
The Caching JAR filesystem provider tracks filesystem provisioning events, including:
- Creating a filesystem
- Reusing an existing filesystem
- Recreating a filesystem if it was previously closed
> Caching JAR filesystem provider tracks filesystem provision events

- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/AbstractJarResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/LazyJarResolver.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/classes/resolvers/jar/LazyJarResolverTest.kt
- `LazyJarResolver` uses `ZipFile` to resolve resource bundles. This is in line with the algorithm that is used to resolve classes by name.
- Improve exception handling in malformed UTF-8 resource bundle content.
- Use explicit types in platform types.
> Lazy JAR resolver uses `ZipFile` to resolve resource bundles

- .idea/copyright/Apache_2_0.xml
- .idea/copyright/profiles_settings.xml
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/dependencies/DependenciesGraphProvider.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/deprecated/DeprecationInfo.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/usages/deprecated/DeprecationUtil.kt
Based on the profiling information:
- Cache `DependencyNode` instances when converting _Structure_ dependency graph to the Plugin Verifier dependency graph
- Reuse `DeprecationInfo` instances for more common cases
> Cache `DependencyNode` and `DeprecationInfo` instances

- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/LazyJarResolver.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/SimpleCompositeResolver.kt
- intellij-plugin-structure/structure-ide-classes/src/main/java/com/jetbrains/plugin/structure/ide/classes/IdeResolverConfiguration.kt
- intellij-plugin-structure/structure-ide-classes/src/main/java/com/jetbrains/plugin/structure/ide/classes/resolver/ProductInfoClassResolver.kt
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/resolver/LayoutComponentsProvider.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/ide/classes/resolver/ProductInfoClassResolverTest.kt
Product Info `bootClassPathJarNames` often share entries with `com.intellij` plugin layout component. 
When creating `Resolver`s, try to reuse an existing resolver for a particular JAR, if that already exists.
For example:
```json
"bootClassPathJarNames" : [
"platform-loader.jar",
"util-8.jar",
]
```
Some entries are shared with:
```json
{
"name": "com.intellij",
"kind": "plugin",
"classPath": [
"lib/platform-loader.jar",
"lib/util-8.jar"
]
}
```
> Product Info `bootClassPathJarNames` share resolvers with core plugin layout components

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/fs/FileSystems.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/fs/FsHandlerFileSystemProvider.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/fs/FsHandlerPath.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/CachingJarFileSystemProvider.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/FsHandleFileSystem.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/UriJarFileSystemProvider.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/ResourceBundleNameSet.kt
- intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/resolvers/SimpleCompositeResolver.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/base/utils/PluginJarTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/classes/resolvers/jar/JarTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/jar/CachingJarFileSystemProviderTest.kt
With `FsHandleFileSystem`, sometimes an underlying filesystem can be closed. This might happen when an low-level implementation, such as `jdk.nio.zipfs.ZipFileSystem` becomes closed.
Introduce `FileSystem`-based implementation that is able to handle this situation. In this case, automatically reopen underlying filesystem without any changes on the client side.
- Introduce `FsHandlerPath` that wraps an arbitrary `Path` and associates it with `FsHandlerFileSystem`. Make this implementation able to reopen itself with a new underlying filesystem.
- Introduce `FsHandlerFileSystemProvider`, an implementation of `java.nio.file.spi.FileSystemProvider` that provides `FsHandlerFileSystem`s and `FsHandlerPath`s.
- Allow the `FsHandleFileSystem` to reopen closed delegated filesystems.
See …
> Introduce reopenable filesystems

- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/Ide.java
- intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/PluginQueryMatcher.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginProvider.java
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginProvision.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginQuery.java
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/domain/IdePluginProviderTest.kt
Semantics of `findPluginByModule` in `PluginProvider` is historically unclear. In this class, module might be a plugin alias or a content module ID.
Add an additional method that allows to query plugins by searching in an explicit places:
- plugin identifier
- plugin name
- plugin aliases
> Query plugin provider for plugin by explicit attributes

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/IdePluginManager.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/loaders/ContentModuleLoader.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/loaders/JarModuleLoader.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/loaders/JarOrDirectoryPluginLoader.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/loaders/JarPluginLoader.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/loaders/LibDirectoryPluginLoader.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/loaders/ModuleFromDescriptorLoader.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/loaders/PluginDirectoryLoader.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/loaders/PluginLoader.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/loaders/PluginLoaderProvider.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/loaders/PluginLoaders.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/loaders/PluginLoadingContext.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/module/FileBasedModuleDescriptorResolver.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/module/InlineModuleDescriptorResolver.kt
- intellij-plugin-structure/structure-intellij/src/test/kotlin/com/jetbrains/plugin/structure/intellij/plugin/module/InlineModuleDescriptorResolverTest.kt
Split `PluginCreator` into distinct classes. Each class is handling a specific resource that will provide a plugin.
- Introduce a `PluginLoadingContext` as a type-safe holder for plugin loading parameters
- Introduce loaders:
* `JarModuleLoader` constructs bundled modules
* `JarOrDirectoryPluginLoader` loads plugins from either a JAR or a extracted plugin directory
* `JarPluginLoader` loads a plugin from a JAR archive
* `LibDirectoryLoader` loads a plugin from the `lib` directory of the plugin
* `ModuleFromDescriptorLoader` loads a plugin module from a file or from an inline CDATA declaration
* `PluginDirectoryLoader` loads a plugin from an extracted directory
The plugin loading logic might be intertwined. One plugin loader might delegate to another loader.
Introduce …
> Extract away plugin component loaders from PluginCreator

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/plugin/Settings.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/utils/FileUtil.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/base/plugin/SettingsTest.kt
There are plugins which contain platform-specific binaries. After decompression, they surpass the original limit.
Increase this limit to 5GB.
> Increase unpacked IntelliJ plugin size to 5GB

- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/PluginVerifierMain.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/CmdOpts.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/PluginParsingConfigurationResolution.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/PluginsParsing.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/repository/LocalPluginRepositoryProvider.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkTrunkApi/CheckTrunkApiParamsBuilder.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/processAllPlugins/ProcessAllPluginsCommand.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/repository/repositories/CompatibilityPredicate.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/repository/repositories/local/LocalPluginRepository.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/repository/repositories/local/LocalPluginRepositoryFactory.kt
- Make the local plugin repository honor plugin problem remapping provided by the CLI.  
- Allow the local repository to be configured with a predicate that indicates compatibility between a plugin and an IDE.  
- Introduce the `-force-offline-compatibility` CLI parameter. When enabled, the `check-plugin-api` command in `-offline` mode will treat any plugin in the local repository as compatible with the major or trunk IDE. This is used for local investigations or tracing API compatibility checks for batches of plugins.
> Local plugin repository honors problem remapping and allows to ignore IDE compatibility rules

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/IdePluginManager.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/plugin/PluginExtractionTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/IdePluginManagerTest.kt
- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/PluginsParsing.kt
- intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/plugin/DefaultPluginDetailsProvider.kt
- Remove parameter from `IdePluginManager` that allows to control whether the extracted directory is deleted. It is never deleted. Extraction and deletion is handled by `PluginArchiveManager`.
- Do not delete resources of failed plugin creations. Such resources might contain dependencies which defeats the purpose of shared cache.
> Do not delete extracted resources outside of Plugin Archive Manager

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/IdePluginManager.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/loaders/JarPluginLoader.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/loaders/LibDirectoryPluginLoader.kt
- intellij-plugin-structure/structure-intellij/src/test/kotlin/com/jetbrains/plugin/structure/intellij/plugin/loaders/JarPluginLoaderTest.kt
- Distinguish between failed plugin descriptor and unavailable plugin descriptor. Log different exception when plugin is not found.
- On JDOM issues, do not log verbose stack trace, as this is an internal issue that cannot be actioned.
- Use `ZipHandler` to quickly detect presence of plugin descriptor in the set of JARs
- Separate JAR and directory parsing to quickly detect descriptor
> Optimize JarPluginLoader in descriptor detection

- intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkPlugin/CheckPluginParamsBuilder.kt
- intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/resolution/DefaultClassResolverProvider.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/dependencies/resolution/DefaultClassResolverProviderTest.kt
If a plugin declares an optional dependency on another plugin that isn’t available in the IDE, that dependency is downloaded from the JetBrains Marketplace.
This was in the Plugin Verifier as per original specs, but has been removed in the new dependency tree based resolution mechanism.
Remove ability to disable this dependency download mechanism, as there is no use-case for that.
> Remove the ability to disable downloading of unavailable optional dependencies

- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/loaders/PluginThemeLoader.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/plugin/loaders/PluginThemeLoaderTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/MockThemePluginsTest.kt
Introduce `PluginThemeLoader` as a standalone class responsible for plugin theme loading.
Extract it away from `PluginCreator`.
> Extract theme loading to a separate class

- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/problems/InvalidDescriptorErrors.kt
- intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/problems/Validator.kt
- intellij-plugin-structure/structure-fleet/src/main/kotlin/com/jetbrains/plugin/structure/fleet/FleetPluginDescriptor.kt
- intellij-plugin-structure/structure-hub/src/main/kotlin/com/jetbrains/plugin/structure/hub/Validator.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginBeanValidator.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/PluginCreationResultResolver.kt
- intellij-plugin-structure/structure-intellij/src/main/resources/com/jetbrains/plugin/structure/intellij/problems/remapping/plugin-problems.json
- intellij-plugin-structure/structure-teamcity/src/main/kotlin/com/jetbrains/plugin/structure/teamcity/Validator.kt
- intellij-plugin-structure/structure-toolbox/src/main/kotlin/com/jetbrains/plugin/structure/toolbox/ToolboxPluginDescriptor.kt
- intellij-plugin-structure/structure-youtrack/src/main/kotlin/com/jetbrains/plugin/structure/youtrack/Validator.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/base/utils/XmlStrings.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/fleet/mock/FleetInvalidPluginsTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/hub/mock/HubInvalidPluginsTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/problems/JsonUrlProblemLevelRemappingManagerTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/BasePluginManagerTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/InvalidPluginsTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/teamcity/mock/TeamcityInvalidPluginsTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/toolbox/mock/ToolboxInvalidPluginsTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/youtrack/mock/YouTrackInvalidPluginTest.kt
- intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/ExistingPluginValidationTest.kt
Introduce `InvalidPluginName` as an error for plugins that do not have a valid name.
This is an _error_ for new IntelliJ plugins and a _warning_ for existing IntelliJ plugins.
Note that plugin names that contain newlines will be automatically checked by the new rule, instead of `ContainsNewLine`.
See [MP-7202](https://youtrack.jetbrains.com/issue/MP-7202)
> Check the plugin name contains only allowed symbols

- CHANGELOG.md
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/Classpath.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/LibDirJarsClasspathProvider.kt
- intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/loaders/LibDirectoryPluginLoader.kt
- intellij-plugin-structure/structure-intellij/src/test/kotlin/com/jetbrains/plugin/structure/intellij/plugin/ClasspathTest.kt
- intellij-plugin-structure/structure-intellij/src/test/kotlin/com/jetbrains/plugin/structure/intellij/plugin/loaders/JarOrDirectoryPluginLoaderTest.kt
- intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/intellij/plugin/dependencies/DependenciesTest.kt
Add all JARs in the 'lib' directory of the plugin to the `classpath`.
This will add additional JARs on top of the JARs that contain content module. Duplicate JARs in the classpath are consolidated with a single origin - explicit JARs have precedence over implicit ones.
See [MP-7742](https://youtrack.jetbrains.com/issue/MP-7742) Plugin Verifier: Scala JARs are not discovered in transitive dependencies
> Add JARs in the 'lib' directory to the plugin classpath
