README.md
Also proofread by copyediting team
=> Minor text improvements in the intro part

intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/PluginVerifier.kt, intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/plugin/PluginDetailsProvider.kt, intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/plugin/PluginDetailsProviderImpl.kt, intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/tests/dependencies/IdeDependencyFinderTest.kt
make verify method public and provide plugin details with structure warning
=> Fixes for Marketplace Verifier

intellij-plugin-structure/structure-ide/src/main/java/com/jetbrains/plugin/structure/ide/IntelliJPlatformProduct.kt
Gateway (GW)
JetBrains Client (JBC)
DataSpell (DS)
=> add new products to IntellijPlatformProduct list

intellij-plugin-verifier/build.gradle
Reverts JetBrains/intellij-plugin-verifier#835
=> Revert "build(deps): bump org.jetbrains.intellij.plugins:structure-intellij from dev to 3.250 in /plugins-verifier-service"

intellij-plugin-structure/build.gradle.kts, intellij-plugin-structure/gradle/libs.versions.toml, intellij-plugin-structure/structure-base/build.gradle.kts, intellij-plugin-structure/structure-classes/build.gradle.kts, intellij-plugin-structure/structure-dotnet/build.gradle.kts, intellij-plugin-structure/structure-fleet/build.gradle.kts, intellij-plugin-structure/structure-ide/build.gradle.kts, intellij-plugin-structure/structure-intellij/build.gradle.kts, intellij-plugin-structure/structure-teamcity/build.gradle.kts, intellij-plugin-structure/structure-toolbox/build.gradle.kts, intellij-plugin-structure/tests/build.gradle.kts
- Use TOML-based Gradle catalog
- Use type-safe dependencies based on such catalog.
=> Plugin Structure: Manage dependencies in a shared TOML file

gradle/libs.versions.toml, ide-diff-builder/build.gradle.kts, intellij-feature-extractor/build.gradle.kts, intellij-feature-extractor/gradle/libs.versions.toml, intellij-plugin-structure/gradle/libs.versions.toml, intellij-plugin-structure/structure-base/build.gradle.kts, intellij-plugin-structure/structure-classes/build.gradle.kts, intellij-plugin-structure/tests/build.gradle.kts, intellij-plugin-verifier/build.gradle.kts, intellij-plugin-verifier/gradle/libs.versions.toml, intellij-plugin-verifier/verifier-cli/build.gradle.kts, intellij-plugin-verifier/verifier-repository/build.gradle.kts, plugins-verifier-service/build.gradle.kts, plugins-verifier-service/gradle/libs.versions.toml
Consolidate dependencies that are shared between at least two modules into global catalog.
=> Consolidate shared dependencies in the global catalog

CHANGELOG.md, intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/OptionsParser.kt, intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/PluginsParsing.kt, intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/output/CliMessages.kt, intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/output/stream/WriterResultPrinter.kt, intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/reporting/LoggingPluginVerificationReportageAggregator.kt
Extract messages parsed by Plugin DevKit in the `PluginVerifierFilter` to separate constants.
=> Extract messages parsed by Plugin DevKit to constants

intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/twoTargets/TwoTargetsResultPrinter.kt
=> TwoTargetsResultPrinter: adjust instruction message on TC

CHANGELOG.md, gradle/libs.versions.toml, intellij-plugin-verifier/build.gradle.kts
- Introduce [Gradle Changelog Plugin](https://github.com/JetBrains/gradle-changelog-plugin)
- Consolidate version names in Changelog (remove `v` prefix in recent versions)
=> Introduce Gradle Changelog Plugin

README.md
In README:
- Document alternative Maven repository,
- improve styling.
=> Document alternative Maven repository and improve styling

intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/IdePlugin.kt, intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/IdePluginImpl.kt, intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/IdePluginManager.kt, intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/InvalidPlugin.kt, intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/PluginCreator.kt, intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/mocks/MockPluginsTest.kt
=> Add info that intellij plugin contains `dotnet` directory

intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/output/markdown/MarkdownOutputTest.kt
Following changes in #1080, Markdown output tests should align with base standard output (_stream_) tests.
=> In unit tests for Output, reuse core logic for Markdown and Stream outputs

gradle/libs.versions.toml
Upgrade `commons-io` to 2.16.1
=> Upgrade commons-io to 2.16.1

intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/plugin/PluginFile.kt, intellij-plugin-structure/structure-dotnet/src/main/kotlin/com/jetbrains/plugin/structure/dotnet/ReSharperPlugin.kt, intellij-plugin-structure/structure-dotnet/src/main/kotlin/com/jetbrains/plugin/structure/dotnet/ReSharperPluginManager.kt, intellij-plugin-structure/structure-fleet/src/main/kotlin/com/jetbrains/plugin/structure/fleet/FleetPlugin.kt, intellij-plugin-structure/structure-teamcity-actions/src/main/kotlin/com/jetbrains/plugin/structure/teamcity/action/TeamCityActionPlugin.kt, intellij-plugin-structure/structure-teamcity-actions/src/main/kotlin/com/jetbrains/plugin/structure/teamcity/action/TeamCityActionPluginManager.kt, intellij-plugin-structure/structure-toolbox/src/main/kotlin/com/jetbrains/plugin/structure/toolbox/ToolboxPlugin.kt, intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/dotnet/mock/DotNetMockPluginTest.kt, intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/teamcity/action/ParseValidFullActionTest.kt, intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/toolbox/mock/ToolboxPluginMockTest.kt
As a part of [MP-6835](https://youtrack.jetbrains.com/issue/MP-6835/Add-a-way-to-fetch-TeamCity-Action-yaml-file) we need a way to get the content of yaml file for parsed TC Actions.
=> Tc actions yaml

intellij-plugin-structure/structure-classes/src/main/java/com/jetbrains/plugin/structure/classes/utils/KtClassResolver.kt
Catch parsing errors when resolving `kotlinx.Metadata`.
Catch documented `IllegalArgumentException` from `kotlinx.metadata` library as not to fail the verification process.
=> Catch parsing errors when resolving kotlinx.metadata

intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/analysis/ClassReachabilityAnalysis.kt
Some classes have malformed annotation descriptors due to obfuscators. For example, a class may contain an annotation with a descriptor filled with `\n` characters.
When the ASM library throws an exception, log these instances at the debug level.
=> Handle malformed annotation descriptors

README.md, intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/filtering/IgnoreCondition.kt, intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/ide/IdeDownloader.kt
Document various formats of plugin specifications.
=> Document plugin specification formats for plugin verifications

intellij-plugin-verifier/verifier-core/src/main/java/com/jetbrains/pluginverifier/results/problems/ClassNotFoundProblem.kt, intellij-plugin-verifier/verifier-core/src/main/java/com/jetbrains/pluginverifier/results/problems/CompatibilityProblem.kt, intellij-plugin-verifier/verifier-core/src/main/java/com/jetbrains/pluginverifier/results/problems/MethodNotFoundProblem.kt, intellij-plugin-verifier/verifier-core/src/main/java/com/jetbrains/pluginverifier/results/problems/PackageNotFoundProblem.kt, intellij-plugin-verifier/verifier-intellij/src/main/kotlin/com/jetbrains/pluginverifier/response/VerifierServiceApi.kt, intellij-plugin-verifier/verifier-intellij/src/main/kotlin/com/jetbrains/pluginverifier/response/VerifierServiceResultConverter.kt, intellij-plugin-verifier/verifier-intellij/src/main/kotlin/com/jetbrains/pluginverifier/response/sarif/SarifFormatConverter.kt, intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/output/BaseOutputPrintTest.kt, intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/output/BaseOutputTest.kt, intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/output/markdown/MarkdownOutputPrintTest.kt, intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/output/marketplace/FullResultResponseTest.kt, intellij-plugin-verifier/verifier-test/src/test/java/com/jetbrains/pluginverifier/output/stream/StreamOutputPrintTest.kt
See [MP-7151](https://youtrack.jetbrains.com/issue/MP-7151) for the description.
=> Introduce critical compatibility problems for Marketplace verification result

intellij-plugin-structure/structure-teamcity-recipes/src/main/kotlin/com/jetbrains/plugin/structure/teamcity/recipe/TeamCityRecipeDescriptor.kt, intellij-plugin-structure/structure-teamcity-recipes/src/main/kotlin/com/jetbrains/plugin/structure/teamcity/recipe/TeamCityRecipeSpec.kt, intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/teamcity/recipe/ParseValidFullRecipeTest.kt, intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/teamcity/recipe/TestData.kt
Renamed one YAML field in the recipe spec
=> TW-92158 Rename the YAML field for the inputs of a referenced recipe

intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/base/problems/InvalidDescriptorErrors.kt, intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/problems/PluginCreationResultResolver.kt, intellij-plugin-structure/structure-toolbox/src/main/kotlin/com/jetbrains/plugin/structure/toolbox/ToolboxPluginDescriptor.kt, intellij-plugin-structure/structure-toolbox/src/main/kotlin/com/jetbrains/plugin/structure/toolbox/ToolboxPluginManager.kt, intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/toolbox/mock/ToolboxInvalidPluginsTest.kt, intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/toolbox/mock/ToolboxPluginMockTest.kt, intellij-plugin-structure/tests/src/test/resources/toolbox/extension.json
+ tests
+ conversion to marketplace compatibility version range
=> TBX-11898: Add support for toolbox apiVersion in descriptor

intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/dependencies/resolution/CompositeDependencyFinder.kt, intellij-plugin-verifier/verifier-repository/src/main/java/com/jetbrains/pluginverifier/repository/repositories/dependency/DependencyPluginRepository.kt
=> Polish dependency finders

intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/plugin/LegacyPluginAnalysis.kt, intellij-plugin-verifier/verifier-intellij/src/main/java/com/jetbrains/pluginverifier/resolution/DefaultClassResolverProvider.kt
=> refactoring: move LegacyPluginAnalysis to structure-intellij

ide-diff-builder/gradle/wrapper/gradle-wrapper.properties, intellij-feature-extractor/gradle/wrapper/gradle-wrapper.properties, intellij-plugin-structure/gradle/wrapper/gradle-wrapper.properties, intellij-plugin-verifier/gradle/wrapper/gradle-wrapper.properties, plugins-verifier-service/gradle/wrapper/gradle-wrapper.properties
Upgrade to [Gradle 8.14.1](https://docs.gradle.org/8.14.1/release-notes.html).
=> Bump Gradle 8.14.1

ide-diff-builder/gradle/wrapper/gradle-wrapper.properties, intellij-feature-extractor/gradle/wrapper/gradle-wrapper.properties, intellij-plugin-structure/gradle/wrapper/gradle-wrapper.properties, intellij-plugin-verifier/gradle/wrapper/gradle-wrapper.properties, plugins-verifier-service/gradle/wrapper/gradle-wrapper.properties
Bump to [Gradle 8.14.2](https://docs.gradle.org/8.14.2/release-notes.html)
=> Bump Gradle 8.14.2

.github/workflows/ide-diff-builder.yml, .github/workflows/intellij-feature-extractor.yml, .github/workflows/intellij-plugin-structure.yml, .github/workflows/intellij-plugin-verifier.yml, .github/workflows/plugins-verifier-service.yml
Update path for collecting test results in GitHub Actions. Align behaviour with the recent Gradle.
=> Update path for collecting test results in GitHub Actions

ide-diff-builder/gradle/wrapper/gradle-wrapper.properties, intellij-feature-extractor/gradle/wrapper/gradle-wrapper.properties, intellij-plugin-structure/gradle/wrapper/gradle-wrapper.properties, intellij-plugin-verifier/gradle/wrapper/gradle-wrapper.properties, plugins-verifier-service/gradle/wrapper/gradle-wrapper.properties
Bump [Gradle 8.14.3](https://docs.gradle.org/8.14.3/release-notes.html).
=> Bump Gradle 8.14.3
